"""Assemble the distributable package from this install.

This is the maintainer's build script. It is tracked in the repository so the checks
below are reviewable, but it is not part of the package: it expects a GAMMA install
around it (`mods/`, `_tools/`, `_release/`), so running it from a clone will not work.
Copy it to `<your GAMMA>/_tools/` to build.

Ships: the mod, the tools, play.bat, the patcher, README, CHANGELOG, LICENSE and docs.
Does not ship: any third-party asset, the generated Seasonal Soundscape mod, or this
install's seasons_config.py (it ships as the example, next to an empty default).

Before packing, the packaged tools are run against a simulated fresh install: a GAMMA
root with ModOrganizer.ini, one profile, an empty appdata and nothing else. A failure
refuses the package.
"""
import io
import os
import shutil
import subprocess
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOOLS = os.path.join(ROOT, "_tools")
OUT = os.path.join(ROOT, "_release")
STAGE = os.path.join(OUT, "Seasons of the Zone")

MOD = "Seasons of the Zone"

# The engine plus the generators for the mod's own content (season table, dial, header
# bars). luacheck.py and check_mcm_strings.py are general X-Ray tools and stay out.
TOOL_FILES = [
    "season.py",
    "build_season_dial.py",
    "build_season_headers.py",
    "build_seasons_ltx.py",
]

EMPTY_CONFIG = '''"""Which mods this install stages per season. The only file to edit.

Empty is the default and is fine: the in-engine layer (light, color, fog, wind, wetness,
the dial, the MCM page) needs nothing here. These tables add the launch-time layers,
which use mods you install yourself. seasons_config.example.py is a complete example.

  TOGGLE_MODS    mods switched on or off per season. Nothing is copied. `above` is the
                 mod yours must outrank; find it with `season.py whowins <file>`.
  LAYOUT         mods whose contents are restaged per season from their archive, for
                 mods that ship one folder per season. Gigabytes move; prefer TOGGLE_MODS.
  SOUND_SRC      the ambience mod whose presets are gated by season. Must be the mod
                 that wins those files.
"""

LAYOUT = {}
TOGGLE_MODS = {}
SOUND_SRC = None
'''


def verify_engine_only():
    """Run season.py status with the configuration hidden."""
    hidden = os.path.join(TOOLS, "seasons_config.py")
    tmp = hidden + ".packing"
    moved = False
    if os.path.isfile(hidden):
        os.rename(hidden, tmp)
        moved = True
    try:
        r = subprocess.run([sys.executable, os.path.join(TOOLS, "season.py"), "status"],
                           capture_output=True, text=True, cwd=ROOT)
        ok = r.returncode == 0 and "Traceback" not in (r.stdout + r.stderr)
        print("  engine-only run        %s" % ("OK" if ok else "** FAILED **"))
        if not ok:
            print((r.stdout + r.stderr)[-900:])
            raise SystemExit("  refusing to package an engine that fails its first run")
    finally:
        if moved:
            os.rename(tmp, hidden)


# The three files season.py rewrites at every launch ship as empty stubs. The mod reads
# all three, and the empty form is what renders the right first-run text.
CRLF = chr(13) + chr(10)

STUB_MODS = CRLF.join([
    "; generated by _tools/season.py on every launch - do not edit by hand",
    "[mods]",
    "staged_for = none",
    "stage_textures = on",
    "stage_sound = on",
    "sound_available = false",
    "sound_cuts = 0",
    "list =",
    "",
])

# season = unknown is the value the mod's mismatch warning ignores.
STUB_STAGED = CRLF.join([
    "[staged]",
    "season = unknown",
    "staging = on",
    "stamped = never",
    "",
])

STUB_XML = CRLF.join([
    '<?xml version="1.0" encoding="windows-1251"?>',
    "",
    "<!-- generated by _tools/season.py - one entry per installed season-scoped",
    "     mod, so the MCM page lists whatever is actually present. Ships empty. -->",
    "<string_table>",
    "</string_table>",
    "",
])


def neutralise_generated(moddir):
    cfg = os.path.join(moddir, "gamedata", "configs")
    for rel, body in (
        (os.path.join(cfg, "season_mods.ltx"), STUB_MODS),
        (os.path.join(cfg, "season_staged.ltx"), STUB_STAGED),
        (os.path.join(cfg, "text", "eng", "ui_mcm_seasons_mods.xml"), STUB_XML),
    ):
        if not os.path.isfile(rel):
            raise SystemExit("  expected generated file missing: %s" % rel)
        io.open(rel, "w", encoding="cp1251", newline="").write(body)
    print("  generated state          3 files reset to first-run stubs")


def verify_fresh_install():
    """Run the packaged tools (status, apply --dry-run, apply) in a sandbox GAMMA root."""
    import tempfile
    sb = os.path.join(tempfile.gettempdir(), "sotz_fresh_install")
    shutil.rmtree(sb, ignore_errors=True)
    game = os.path.join(sb, "ANOMALY")
    root = os.path.join(sb, "GAMMA")
    os.makedirs(os.path.join(game, "appdata"))
    os.makedirs(os.path.join(root, "profiles", "Default"))
    os.makedirs(os.path.join(root, "downloads"))
    os.makedirs(os.path.join(root, "mods", "Some Other Mod"))
    io.open(os.path.join(root, "ModOrganizer.ini"), "w", encoding="utf-8").write(
        "[General]" + chr(10)
        + "gamePath=@ByteArray(" + game.replace(chr(92), chr(92) * 2) + ")" + chr(10)
        + "selected_profile=@ByteArray(Default)" + chr(10))
    modlist = os.path.join(root, "profiles", "Default", "modlist.txt")
    crlf = chr(13) + chr(10)
    header = "# This file was automatically generated by Mod Organizer." + crlf
    io.open(modlist, "w", encoding="utf-8", newline="").write(
        header + "+" + MOD + crlf + "+Some Other Mod" + crlf)
    copytree(os.path.join(STAGE, "mods"), os.path.join(root, "mods"))
    copytree(os.path.join(STAGE, "_tools"), os.path.join(root, "_tools"))

    ok = True
    for args in (["status"], ["apply", "--dry-run"], ["apply"]):
        r = subprocess.run([sys.executable, os.path.join(root, "_tools", "season.py")] + args,
                           capture_output=True, text=True, cwd=root)
        text = r.stdout + r.stderr
        good = r.returncode == 0 and "Traceback" not in text
        print("  fresh install: season.py %-16s %s" % (" ".join(args), "OK" if good else "** FAILED **"))
        if not good:
            print(text[-1200:])
            ok = False
    staged = io.open(os.path.join(root, "mods", MOD, "gamedata", "configs",
                                  "season_staged.ltx"), encoding="cp1251").read()
    ml = io.open(modlist, encoding="utf-8", newline="").read()
    if "season = unknown" in staged or "stamped = never" in staged:
        print("  fresh install: season_staged.ltx was not written by apply   ** FAILED **")
        ok = False
    if not ml.startswith(header) or ("+" + MOD + crlf) not in ml:
        print("  fresh install: modlist.txt damaged                          ** FAILED **")
        ok = False
    shutil.rmtree(sb, ignore_errors=True)
    if not ok:
        raise SystemExit("  refusing to package: the tooling fails on a fresh install")


def copytree(src, dst):
    n = 0
    for root, _, files in os.walk(src):
        for f in files:
            p = os.path.join(root, f)
            rel = os.path.relpath(p, src)
            t = os.path.join(dst, rel)
            os.makedirs(os.path.dirname(t), exist_ok=True)
            shutil.copy2(p, t)
            n += 1
    return n


def check_savedgames_repair(moddir):
    """Listing $app_data_root$ costs the engine its registry for the savedgames folder
    underneath it, and CALifeUpdateManager::load then fatals with "Cannot find the
    specified saved game" on a save that is plainly on disk. MCM calls on_mcm_load at
    startup, so it happens on every load, not only when the menu is opened. Every appdata
    listing must be followed by a $game_saves$ listing that puts the registry back.

    This shipped unguarded once and every save load crashed."""
    listed = 0
    for root, _, files in os.walk(moddir):
        for f in sorted(files):
            if not f.lower().endswith(".script"):
                continue
            p = os.path.join(root, f)
            lines = io.open(p, encoding="latin-1", newline="").read().splitlines()
            for i, line in enumerate(lines):
                if 'file_list_open_ex("$app_data_root$"' not in line:
                    continue
                listed += 1
                if 'file_list_open_ex("$game_saves$"' not in "\n".join(lines[i:i + 40]):
                    raise SystemExit(
                        "  refusing to package: %s lists $app_data_root$ at line %d and\n"
                        "  never re-lists $game_saves$. Saves would stop loading."
                        % (os.path.basename(p), i + 1))
    print("  savedgames guard       %3d appdata listing(s), each repaired" % listed)


def main():
    verify_engine_only()

    shutil.rmtree(STAGE, ignore_errors=True)
    os.makedirs(STAGE)

    n = copytree(os.path.join(ROOT, "mods", MOD), os.path.join(STAGE, "mods", MOD))
    print("  mod                    %3d files" % n)
    neutralise_generated(os.path.join(STAGE, "mods", MOD))
    check_savedgames_repair(os.path.join(STAGE, "mods", MOD))

    td = os.path.join(STAGE, "_tools")
    os.makedirs(td)
    for f in TOOL_FILES:
        shutil.copy2(os.path.join(TOOLS, f), os.path.join(td, f))
    io.open(os.path.join(td, "seasons_config.py"), "w",
            encoding="utf-8", newline="").write(EMPTY_CONFIG)
    live = os.path.join(TOOLS, "seasons_config.py")
    if os.path.isfile(live):
        shutil.copy2(live, os.path.join(td, "seasons_config.example.py"))
    print("  tools                  %3d files  (+ empty config, + worked example)" % len(TOOL_FILES))

    shutil.copy2(os.path.join(ROOT, "play.bat"), os.path.join(STAGE, "play.bat"))
    shutil.copy2(os.path.join(OUT, "README.md"), os.path.join(STAGE, "README.md"))
    for extra in ("CHANGELOG.md", "LICENSE"):
        p = os.path.join(OUT, extra)
        if os.path.isfile(p):
            shutil.copy2(p, os.path.join(STAGE, extra))

    nd = copytree(os.path.join(OUT, "docs"), os.path.join(STAGE, "docs"))
    print("  docs                   %3d files" % nd)

    np = copytree(os.path.join(OUT, "patches"), os.path.join(STAGE, "patches"))
    print("  patches                %3d files" % np)

    # INVERNO's script must never ship, in any form.
    for root, _, files in os.walk(STAGE):
        for f in files:
            if f.lower() == "yawm_snowfall.script":
                raise SystemExit("  refusing to package %s"
                                 % os.path.join(root, f))

    verify_fresh_install()

    zp = os.path.join(OUT, "SeasonsOfTheZone.zip")
    if os.path.isfile(zp):
        os.remove(zp)
    total = 0
    with zipfile.ZipFile(zp, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for root, _, files in os.walk(STAGE):
            for f in files:
                p = os.path.join(root, f)
                z.write(p, os.path.join(MOD, os.path.relpath(p, STAGE)))
                total += 1
    print()
    print("  %-38s %4d files  %6.1f MB" % (os.path.basename(zp), total,
                                           os.path.getsize(zp) / 1048576.0))


if __name__ == "__main__":
    main()
