"""Pull the real Zone's weather and leave it where the game can read it.

Seasons of the Zone already runs its calendar on real dates. This closes the loop on
temperature: instead of climate normals for the region, the day's high and low come from
what Chornobyl is actually doing. The in-game curve between them is still modelled - the
game's day is accelerated and its sky is Atmospherics', so only the endpoints are real.

What leaves the machine: a fixed latitude and longitude for Chornobyl. Not the player's
location, no account, no key, no identifiers. The response is about 500 bytes.

This must never be the reason a launch fails. Every failure path - no network, a slow
endpoint, a malformed response, a read-only disk - leaves the previous file alone and
exits 0. Without a usable file the game falls back to climate normals and says so.

  python fetch_weather.py              fetch if the cache is stale
  python fetch_weather.py --force      fetch regardless
  python fetch_weather.py --offline    do nothing, for testing the fallback
  python fetch_weather.py --show       print what the game would read
"""
import argparse
import datetime
import io
import json
import os
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.join(os.path.dirname(HERE), "mods", "Seasons of the Zone")
OUT = os.path.join(MOD, "gamedata", "configs", "season_weather.ltx")

# Chornobyl. Slavutych (51.5194, 30.7511) is the nearest inhabited town and reads within
# a degree of this; the Zone itself is the more honest anchor for a mod about the Zone.
PLACE = "Chornobyl"
LAT, LON = 51.2763, 30.2219
TZ = "Europe/Kyiv"

URL = ("https://api.open-meteo.com/v1/forecast"
       "?latitude=%s&longitude=%s"
       "&daily=temperature_2m_max,temperature_2m_min,weather_code"
       "&timezone=%s&forecast_days=2")

REFRESH_HOURS = 6
TIMEOUT = 12

# WMO codes, collapsed onto the cycle names Atmospherics uses. Only ever advisory: the
# sky the player is standing under is the game's, not Chornobyl's.
WMO = [
    ({0}, "clear"), ({1, 2}, "partly"), ({3}, "cloudy"),
    ({45, 48}, "foggy"),
    ({51, 53, 55, 56, 57, 61, 63, 65, 66, 67, 80, 81, 82}, "rain"),
    ({71, 73, 75, 77, 85, 86}, "snow"),
    ({95, 96, 99}, "storm"),
]


def code_to_cycle(code):
    for codes, name in WMO:
        if code in codes:
            return name
    return "cloudy"


def read_existing(section="weather"):
    """One section of the ltx.

    Section-aware on purpose: [weather] and [weather_next] carry the same key names, so a
    flat read silently hands back tomorrow's numbers labelled as today's. The Lua side
    reads this file too and has to make the same distinction.
    """
    if not os.path.exists(OUT):
        return {}
    out, here = {}, None
    try:
        for line in io.open(OUT, encoding="utf-8"):
            line = line.split(";")[0].strip()
            if line.startswith("[") and line.endswith("]"):
                here = line[1:-1].strip()
                continue
            if here == section and "=" in line:
                k, v = line.split("=", 1)
                out[k.strip()] = v.strip()
    except Exception:
        return {}
    return out


def is_fresh(existing):
    stamp = existing.get("fetched_at")
    if not stamp:
        return False
    try:
        when = datetime.datetime.strptime(stamp, "%Y-%m-%d %H:%M")
    except ValueError:
        return False
    age = (datetime.datetime.now() - when).total_seconds() / 3600.0
    return 0 <= age < REFRESH_HOURS


def fetch():
    url = URL % (LAT, LON, TZ.replace("/", "%2F"))
    with urllib.request.urlopen(url, timeout=TIMEOUT) as r:
        return json.load(r)


def to_rows(payload):
    d = payload["daily"]
    rows = []
    for i, day in enumerate(d["time"]):
        rows.append({
            "date": day,
            "high": float(d["temperature_2m_max"][i]),
            "low": float(d["temperature_2m_min"][i]),
            "cycle": code_to_cycle(int(d["weather_code"][i])),
        })
    return rows


TEMPLATE = """; Seasons of the Zone - the real Zone's weather.
;
; Generated by _tools/fetch_weather.py, which play.bat runs before launching. Do not
; hand-edit: the next run overwrites it. Deleting it is safe - the game falls back to
; climate normals for the region and marks the reading as modelled.
;
; Only the day's endpoints are real. The curve between them is modelled, because the
; game's day is accelerated and its sky belongs to Atmospherics, not to Chornobyl.

[weather]
source       = open-meteo
place        = %(place)s
fetched_at   = %(fetched_at)s
date         = %(date)s
high         = %(high).1f
low          = %(low).1f
cycle        = %(cycle)s
freezing     = %(freezing)s

[weather_next]
date         = %(n_date)s
high         = %(n_high).1f
low          = %(n_low).1f
cycle        = %(n_cycle)s
freezing     = %(n_freezing)s
"""


def write(rows):
    today = rows[0]
    nxt = rows[1] if len(rows) > 1 else rows[0]
    body = TEMPLATE % {
        "place": PLACE,
        "fetched_at": datetime.datetime.now().strftime("%Y-%m-%d %H:%M"),
        "date": today["date"], "high": today["high"], "low": today["low"],
        "cycle": today["cycle"],
        "freezing": "true" if today["low"] <= 0.0 else "false",
        "n_date": nxt["date"], "n_high": nxt["high"], "n_low": nxt["low"],
        "n_cycle": nxt["cycle"],
        "n_freezing": "true" if nxt["low"] <= 0.0 else "false",
    }
    tmp = OUT + ".tmp"
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with io.open(tmp, "w", encoding="utf-8", newline="\r\n") as fh:
        fh.write(body)
    os.replace(tmp, OUT)       # atomic: the game never sees a half-written file


def show():
    e = read_existing()
    if not e:
        print("  no season_weather.ltx - the game will use climate normals")
        return
    print("  %s, %s: high %s low %s, %s%s"
          % (e.get("place", "?"), e.get("date", "?"), e.get("high", "?"),
             e.get("low", "?"), e.get("cycle", "?"),
             "  FREEZING" if e.get("freezing") == "true" else ""))
    print("  fetched %s (%s)" % (e.get("fetched_at", "?"),
                                 "fresh" if is_fresh(e) else "stale"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--offline", action="store_true")
    ap.add_argument("--show", action="store_true")
    a = ap.parse_args()

    if a.show:
        show()
        return 0
    if a.offline:
        print("  offline: leaving season_weather.ltx as it is")
        return 0

    existing = read_existing()
    if not a.force and is_fresh(existing):
        print("  weather is under %dh old, not refetching" % REFRESH_HOURS)
        return 0

    try:
        rows = to_rows(fetch())
    except Exception as e:
        # Never the reason a launch fails.
        print("  weather unavailable (%s) - keeping what is there" % type(e).__name__)
        return 0

    try:
        write(rows)
    except Exception as e:
        print("  could not write season_weather.ltx (%s) - carrying on" % type(e).__name__)
        return 0

    t = rows[0]
    print("  %s %s: high %.1f low %.1f, %s%s"
          % (PLACE, t["date"], t["high"], t["low"], t["cycle"],
             "  FREEZING" if t["low"] <= 0.0 else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
