"""Run the SHIPPED configure.py - its commands and its window - against scratch installs.

The tool writes the one file users used to get wrong by hand, so each case checks what
it wrote the way the game will read it: season.py's own `status` has to accept the file,
and `apply --dry-run` has to place the mods where the tool said. Hand-written parts of
an existing config have to come through untouched.

  python _tools/test_configure.py
"""
import io
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLS = ("season.py", "config_edit.py", "configure.py")
CRLF = "\r\n"

# highest priority first, as modlist.txt lists them
MODS = [
    ("Winter Overlay", False, ["textures/grass/b.dds"]),
    ("Winter Pack", False, ["textures/grass/a.dds", "textures/grass/b.dds",
                            "textures/terrain/t.dds"]),
    ("Grass Compat", True, ["textures/grass/a.dds"]),
    ("Winter Maps", False, ["textures/map/m.dds"]),
    ("Map Pack", True, ["textures/map/m.dds"]),
    ("Lonely Mod", False, ["scripts/lonely.script"]),
    ("Base Grass", True, ["textures/grass/a.dds", "textures/grass/b.dds",
                          "textures/grass/c.dds"]),
    ("Seasons of the Zone", True, ["scripts/zzz_seasons_of_the_zone.script"]),
]


def install(root, config=None, mods=MODS):
    os.makedirs(os.path.join(root, "_tools"))
    for f in TOOLS:
        shutil.copy2(os.path.join(HERE, f), os.path.join(root, "_tools", f))
    if config is not None:
        io.open(os.path.join(root, "_tools", "seasons_config.py"), "w",
                encoding="utf-8").write(config)
    io.open(os.path.join(root, "ModOrganizer.ini"), "w", encoding="utf-8").write(
        "[General]" + CRLF + "selected_profile=@ByteArray(Default)" + CRLF)
    os.makedirs(os.path.join(root, "profiles", "Default"))
    lines = ["# This file was automatically generated by Mod Organizer."]
    for name, on, files in mods:
        lines.append(("+" if on else "-") + name)
        for f in files:
            p = os.path.join(root, "mods", name, "gamedata", *f.split("/"))
            os.makedirs(os.path.dirname(p), exist_ok=True)
            io.open(p, "w").write(name)
    io.open(os.path.join(root, "profiles", "Default", "modlist.txt"), "w",
            encoding="utf-8", newline="").write(CRLF.join(lines) + CRLF)


def run(root, *args, tool="configure.py"):
    r = subprocess.run([sys.executable, os.path.join(root, "_tools", tool)] + list(args),
                       capture_output=True, text=True, cwd=root, encoding="utf-8",
                       errors="replace")
    assert "Traceback" not in r.stdout + r.stderr, r.stdout + r.stderr
    return r.returncode, r.stdout + r.stderr


def config(root):
    p = os.path.join(root, "_tools", "seasons_config.py")
    return io.open(p, encoding="utf-8").read() if os.path.isfile(p) else None


def table(root):
    ns = {}
    exec(config(root), ns)
    return ns.get("TOGGLE_MODS", {}), ns.get("EVENTS", {})


def accepted(root):
    rc, out = run(root, "status", tool="season.py")
    assert rc == 0 and "needs fixing" not in out, "season.py refused it:\n" + out


CASES = []


def case(fn):
    CASES.append(fn)
    return fn


@case
def t_add_writes_a_config_the_game_accepts():
    with tempfile.TemporaryDirectory() as d:
        install(d)
        rc, out = run(d, "add", "Winter Pack", "--when", "winter", "winter_snow")
        assert rc == 0 and "added" in out, out
        t, _ = table(d)
        assert t == {"Winter Pack": {"when": ("winter", "winter_snow"),
                                     "above": "Grass Compat"}}, t
        accepted(d)
    return "new file, and Grass Compat - the highest mod sharing a file - as the anchor"


@case
def t_the_anchor_is_where_the_mod_ends_up():
    """apply puts the mod directly above its anchor. The tool's anchor has to leave it above
    every enabled mod that ships the same files."""
    # Winter Pack starts at the bottom, under both mods it shares files with, so apply has
    # to lift it past both - an anchor on the lower one would leave it under the higher
    low = [m for m in MODS if m[0] != "Winter Pack"] + [m for m in MODS if m[0] == "Winter Pack"]
    with tempfile.TemporaryDirectory() as d:
        install(d, mods=low)
        run(d, "add", "Winter Pack", "--when", "winter")
        rc, out = run(d, "apply", "--season", "winter", tool="season.py")
        assert rc == 0, out
        body = [l.strip() for l in io.open(os.path.join(d, "profiles", "Default",
                                                         "modlist.txt"))][1:]
        pos = {l[1:]: i for i, l in enumerate(body)}
        assert body[pos["Winter Pack"]] == "+Winter Pack", "not switched on"
        for rival in ("Grass Compat", "Base Grass"):
            assert pos["Winter Pack"] < pos[rival], "sits below %s, which shares files" % rival
    return "switched on in winter, and above both mods that share its files"


@case
def t_names_and_seasons_are_forgiving_but_not_guessed():
    with tempfile.TemporaryDirectory() as d:
        install(d)
        run(d, "add", "Winter Pack", "--when", "winter")
        rc, out = run(d, "add", "winter pack", "--when", "deep winter")
        assert rc == 0 and "changed" in out and "as it was" in out, out
        t, _ = table(d)
        assert t["Winter Pack"]["when"] == ("winter_snow",), t
        before = config(d)
        rc, out = run(d, "add", "Winter Pak", "--when", "winter")
        assert rc == 1 and "Did you mean" in out and "Winter Pack" in out, out
        rc, out = run(d, "add", "Winter Pack", "--when", "wintr")
        assert rc == 1 and "not a season" in out, out
        assert config(d) == before, "a refused command changed the file"
    return "case and \"deep winter\" accepted; a typo gets suggestions and changes nothing"


@case
def t_a_rival_seasonal_mod_is_named_not_chosen():
    """Which of two seasonal mods wins is the user's call. The tool anchors on the rest and
    says how to make it win the other."""
    with tempfile.TemporaryDirectory() as d:
        install(d)
        run(d, "add", "Winter Pack", "--when", "winter", "winter_snow")
        rc, out = run(d, "add", "Winter Overlay", "--when", "winter")
        assert rc == 0, out
        t, _ = table(d)
        assert t["Winter Overlay"]["above"] == "Base Grass", t
        assert '--above "Winter Pack"' in out, "the rival was not named:\n" + out
        rc, out = run(d, "add", "Winter Overlay", "--when", "winter", "--above", "Winter Pack")
        assert rc == 0 and table(d)[0]["Winter Overlay"]["above"] == "Winter Pack", out
        accepted(d)
    return "anchored on Base Grass, with Winter Pack named; --above makes it win"


@case
def t_a_mod_that_shares_nothing_stays_where_it_is():
    with tempfile.TemporaryDirectory() as d:
        install(d)
        rc, out = run(d, "add", "Lonely Mod", "--when", "spring")
        assert rc == 0 and "stays where it is" in out, out
        before = [l.strip()[1:] for l in io.open(os.path.join(
            d, "profiles", "Default", "modlist.txt"))][1:]
        run(d, "apply", "--season", "spring", tool="season.py")
        after = [l.strip()[1:] for l in io.open(os.path.join(
            d, "profiles", "Default", "modlist.txt"))][1:]
        assert before == after, "the modlist order changed"
    return "anchored on the mod under it; the order does not move"


@case
def t_events_can_be_made_used_and_removed():
    with tempfile.TemporaryDirectory() as d:
        install(d)
        rc, out = run(d, "event", "christmas", "12-24", "12-26")
        assert rc == 0, out
        rc, out = run(d, "add", "Winter Maps", "--when", "christmas")
        assert rc == 0, out
        t, e = table(d)
        assert e == {"christmas": ((12, 24), (12, 26))} and \
            t["Winter Maps"]["when"] == ("christmas",), (t, e)
        accepted(d)
        rc, out = run(d, "event", "christmas", "--remove")
        assert rc == 1 and "Winter Maps" in out, "removed an event a mod still uses"
        run(d, "remove", "Winter Maps")
        rc, out = run(d, "event", "christmas", "--remove")
        assert rc == 0 and table(d)[1] == {}, out
        rc, out = run(d, "event", "halloween", "13-01")
        assert rc == 1 and "month-day" in out, out
    return "made, scoped, refused while in use, removed; a bad date refused"


HAND = '''"""My config."""

# grass from the archive
LAYOUT = {}

TOGGLE_MODS = {
    # the snow, both winters
    "Winter Pack": {
        "seasons": ("winter", "winter_snow"),   # the old spelling
        "above": "Grass Compat",
    },
}
SOUND_SRC = None  # no ambience mod
PERIODS = {}
EVENTS = {}
'''


@case
def t_what_was_written_by_hand_is_kept():
    with tempfile.TemporaryDirectory() as d:
        install(d, config=HAND)
        rc, out = run(d, "add", "Map Pack", "--when", "summer")
        assert rc == 0, out
        new = config(d).split("\n")
        old = HAND.split("\n")
        # every line of the hand-written file, in order, and the new entry after it
        it = iter(new)
        missing = [l for l in old if not any(l == x for x in it)]
        assert not missing, "lost: %s" % missing
        assert io.open(os.path.join(d, "_tools", "seasons_config.py.bak"),
                       encoding="utf-8").read() == HAND, "the backup is not the old file"
        accepted(d)
    return "every hand-written line and comment kept, and the old file in .bak"


GHOUL = '''LAYOUT = {}
TOGGLE_MODS = {
    "Winter Pack": {
        "when": ("winter_snow",),
        "above": "Grass Compat",
    },"Map Pack": {
        "when": ("summer,spring"),
        "above": "Base Grass",
    },
}
SOUND_SRC = None
PERIODS = {}
EVENTS = {}
TOGGLE_MODS = {}
'''


@case
def t_a_ghoul_config_is_repaired_on_save():
    """The two mistakes from the Discord thread: the table thrown away by an empty one
    below it, and ("summer,spring")."""
    with tempfile.TemporaryDirectory() as d:
        install(d, config=GHOUL)
        rc, out = run(d, "status", tool="season.py")
        assert rc != 0, "the broken file was accepted as it is"
        rc, out = run(d, "list")
        assert "saving removes that line" in out and "right shape" in out, out
        rc, out = run(d, "add", "Lonely Mod", "--when", "spring")
        assert rc == 0, out
        t, _ = table(d)
        assert t["Map Pack"]["when"] == ("summer", "spring"), t
        assert set(t) == {"Winter Pack", "Map Pack", "Lonely Mod"}, t
        assert config(d).count("TOGGLE_MODS =") == 1, "the empty table is still there"
        accepted(d)
    return "one TOGGLE_MODS left, (\"summer\", \"spring\"), and season.py accepts it"


@case
def t_a_file_python_cannot_read_is_left_alone():
    bad = HAND.replace('("winter", "winter_snow")', '(, "winter_snow")')
    with tempfile.TemporaryDirectory() as d:
        install(d, config=bad)
        rc, out = run(d, "add", "Map Pack", "--when", "summer")
        assert rc == 1 and "can't be read" in out and "line 9" in out, out
        assert config(d) == bad, "an unreadable file was overwritten"
    return "refused, with the line, and the file untouched"


@case
def t_the_window_edits_and_saves():
    """The window, driven the way a click would, in a process of its own."""
    driver = r'''
import sys
sys.path.insert(0, sys.argv[1])
import tkinter as tk
import config_edit as ce
import configure
root = tk.Tk()
root.withdraw()
cal, inst = ce.Calendar(), ce.Install()
app = configure.App(root, cal, inst)
app.select("Winter Pack")
app.set_when("Winter Pack", ["winter", "winter_snow"])
app.add_event("halloween", (10, 31), (10, 31))
app.select("Map Pack")
app.set_when("Map Pack", ["summer"])
app.set_when("Map Pack", [])
print("dirty before", cal.dirty())
print("saved", app.save(quiet=True))
print("dirty after", cal.dirty())
root.destroy()
'''
    with tempfile.TemporaryDirectory() as d:
        install(d)
        p = os.path.join(d, "drive.py")
        io.open(p, "w", encoding="utf-8").write(driver)
        r = subprocess.run([sys.executable, p, os.path.join(d, "_tools")], cwd=d,
                           capture_output=True, text=True)
        out = r.stdout + r.stderr
        assert r.returncode == 0 and "saved True" in out, out
        assert "dirty before True" in out and "dirty after False" in out, out
        t, e = table(d)
        assert set(t) == {"Winter Pack"}, "unticking everything did not take it off: %s" % t
        assert t["Winter Pack"] == {"when": ("winter", "winter_snow", "halloween"),
                                    "above": "Grass Compat"}, t
        assert e == {"halloween": ((10, 31), (10, 31))}, e
        accepted(d)
    return "ticks, a new event and an untick saved; season.py accepts the file"


@case
def t_a_real_config_comes_back_unchanged():
    """The live install's config, loaded and written back with nothing changed."""
    live = os.path.join(os.environ.get("GAMMA_INSTALL", r"D:\GAMMA"), "_tools",
                        "seasons_config.py")
    if not os.path.isfile(live):
        return "no live config here - skipped"
    sys.path.insert(0, HERE)
    import config_edit as ce
    cal = ce.Calendar(live)
    assert not cal.error and not cal.dirty(), (cal.error, cal.fixes)
    text, kept = cal.render()
    assert kept and text.replace("\n", cal.nl) == cal.original, "a no-op save changes it"
    return "%d entries, byte for byte" % len(cal.toggle)


if __name__ == "__main__":
    print("  running the shipped configure.py against scratch installs")
    bad = 0
    for fn in CASES:
        try:
            print("  PASS  %-48s %s" % (fn.__name__[2:], fn()))
        except AssertionError as e:
            bad += 1
            print("  FAIL  %-48s %s" % (fn.__name__[2:], e))
        except Exception as e:
            bad += 1
            print("  ERROR %-48s %s: %s" % (fn.__name__[2:], type(e).__name__, e))
    print("\n  %d/%d passed" % (len(CASES) - bad, len(CASES)))
    sys.exit(1 if bad else 0)
