"""Run the SHIPPED configure.py - its commands and its window - against scratch installs.

The tool writes the one file users used to get wrong by hand, so each case checks what
it wrote the way the game will read it: season.py's own `status` has to accept the file,
and `apply --dry-run` has to place the mods where the tool said. Hand-written parts of
an existing config have to come through untouched.

  python _tools/test_configure.py
"""
import io
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLS = ("season.py", "config_edit.py", "configure.py", "build_season_dial.py")
MOD_CFG = os.path.join(os.path.dirname(HERE), "mods", "Seasons of the Zone", "gamedata",
                       "configs", "seasons_of_the_zone.ltx")
CRLF = "\r\n"

# highest priority first, as modlist.txt lists them
MODS = [
    ("Winter Overlay", False, ["textures/grass/b.dds"]),
    ("Winter Pack", False, ["textures/grass/a.dds", "textures/grass/b.dds",
                            "textures/terrain/t.dds"]),
    ("Grass Compat", True, ["textures/grass/a.dds"]),
    ("Winter Maps", False, ["textures/map/m.dds"]),
    ("Map Pack", True, ["textures/map/m.dds"]),
    ("Lonely Mod", False, ["scripts/lonely.script"]),
    ("Base Grass", True, ["textures/grass/a.dds", "textures/grass/b.dds",
                          "textures/grass/c.dds"]),
    ("Seasons of the Zone", True, ["scripts/zzz_seasons_of_the_zone.script"]),
]


def install(root, config=None, mods=MODS):
    os.makedirs(os.path.join(root, "_tools"))
    for f in TOOLS:
        shutil.copy2(os.path.join(HERE, f), os.path.join(root, "_tools", f))
    if config is not None:
        io.open(os.path.join(root, "_tools", "seasons_config.py"), "w",
                encoding="utf-8").write(config)
    io.open(os.path.join(root, "ModOrganizer.ini"), "w", encoding="utf-8").write(
        "[General]" + CRLF + "selected_profile=@ByteArray(Default)" + CRLF)
    os.makedirs(os.path.join(root, "profiles", "Default"))
    lines = ["# This file was automatically generated by Mod Organizer."]
    for name, on, files in mods:
        lines.append(("+" if on else "-") + name)
        for f in files:
            p = os.path.join(root, "mods", name, "gamedata", *f.split("/"))
            os.makedirs(os.path.dirname(p), exist_ok=True)
            io.open(p, "w").write(name)
    io.open(os.path.join(root, "profiles", "Default", "modlist.txt"), "w",
            encoding="utf-8", newline="").write(CRLF.join(lines) + CRLF)


def run(root, *args, tool="configure.py", env=None):
    r = subprocess.run([sys.executable, os.path.join(root, "_tools", tool)] + list(args),
                       capture_output=True, text=True, cwd=root, encoding="utf-8",
                       errors="replace", env=env)
    assert "Traceback" not in r.stdout + r.stderr, r.stdout + r.stderr
    return r.returncode, r.stdout + r.stderr


def config(root):
    p = os.path.join(root, "_tools", "seasons_config.py")
    return io.open(p, encoding="utf-8").read() if os.path.isfile(p) else None


def table(root):
    ns = {}
    exec(config(root), ns)
    return ns.get("TOGGLE_MODS", {}), ns.get("EVENTS", {})


def calendar_of(root):
    ns = {}
    exec(config(root), ns)
    return ns.get("CALENDAR")


def with_mod(root):
    """The parts of the mod a calendar needs: its configs, for the file the game reads and
    the dial's colors, and its textures folder, for the dial."""
    gd = os.path.join(root, "mods", "Seasons of the Zone", "gamedata")
    os.makedirs(os.path.join(gd, "configs"))
    os.makedirs(os.path.join(gd, "textures"))
    shutil.copy2(MOD_CFG, os.path.join(gd, "configs"))
    return (os.path.join(gd, "configs", "season_calendar.ltx"),
            os.path.join(gd, "textures"))


def drawn(tex):
    return len([f for f in os.listdir(tex) if f.startswith("ui_seasons_dial_c")])


def accepted(root):
    rc, out = run(root, "status", tool="season.py")
    assert rc == 0 and "needs fixing" not in out, "season.py refused it:\n" + out


CASES = []


def case(fn):
    CASES.append(fn)
    return fn


@case
def t_add_writes_a_config_the_game_accepts():
    with tempfile.TemporaryDirectory() as d:
        install(d)
        rc, out = run(d, "add", "Winter Pack", "--when", "winter", "winter_snow")
        assert rc == 0 and "added" in out, out
        t, _ = table(d)
        assert t == {"Winter Pack": {"when": ("winter", "winter_snow"),
                                     "above": "Grass Compat"}}, t
        accepted(d)
    return "new file, and Grass Compat - the highest mod sharing a file - as the anchor"


@case
def t_the_anchor_is_where_the_mod_ends_up():
    """apply puts the mod directly above its anchor. The tool's anchor has to leave it above
    every enabled mod that ships the same files."""
    # Winter Pack starts at the bottom, under both mods it shares files with, so apply has
    # to lift it past both - an anchor on the lower one would leave it under the higher
    low = [m for m in MODS if m[0] != "Winter Pack"] + [m for m in MODS if m[0] == "Winter Pack"]
    with tempfile.TemporaryDirectory() as d:
        install(d, mods=low)
        run(d, "add", "Winter Pack", "--when", "winter")
        rc, out = run(d, "apply", "--season", "winter", tool="season.py")
        assert rc == 0, out
        body = [l.strip() for l in io.open(os.path.join(d, "profiles", "Default",
                                                         "modlist.txt"))][1:]
        pos = {l[1:]: i for i, l in enumerate(body)}
        assert body[pos["Winter Pack"]] == "+Winter Pack", "not switched on"
        for rival in ("Grass Compat", "Base Grass"):
            assert pos["Winter Pack"] < pos[rival], "sits below %s, which shares files" % rival
    return "switched on in winter, and above both mods that share its files"


@case
def t_names_and_seasons_are_forgiving_but_not_guessed():
    with tempfile.TemporaryDirectory() as d:
        install(d)
        run(d, "add", "Winter Pack", "--when", "winter")
        rc, out = run(d, "add", "winter pack", "--when", "deep winter")
        assert rc == 0 and "changed" in out and "as it was" in out, out
        t, _ = table(d)
        assert t["Winter Pack"]["when"] == ("winter_snow",), t
        before = config(d)
        rc, out = run(d, "add", "Winter Pak", "--when", "winter")
        assert rc == 1 and "Did you mean" in out and "Winter Pack" in out, out
        rc, out = run(d, "add", "Winter Pack", "--when", "wintr")
        assert rc == 1 and "not a season" in out, out
        assert config(d) == before, "a refused command changed the file"
    return "case and \"deep winter\" accepted; a typo gets suggestions and changes nothing"


@case
def t_a_rival_seasonal_mod_is_named_not_chosen():
    """Which of two seasonal mods wins is the user's call. The tool anchors on the rest and
    says how to make it win the other."""
    with tempfile.TemporaryDirectory() as d:
        install(d)
        run(d, "add", "Winter Pack", "--when", "winter", "winter_snow")
        rc, out = run(d, "add", "Winter Overlay", "--when", "winter")
        assert rc == 0, out
        t, _ = table(d)
        assert t["Winter Overlay"]["above"] == "Base Grass", t
        assert '--above "Winter Pack"' in out, "the rival was not named:\n" + out
        rc, out = run(d, "add", "Winter Overlay", "--when", "winter", "--above", "Winter Pack")
        assert rc == 0 and table(d)[0]["Winter Overlay"]["above"] == "Winter Pack", out
        accepted(d)
    return "anchored on Base Grass, with Winter Pack named; --above makes it win"


@case
def t_a_mod_that_shares_nothing_stays_where_it_is():
    with tempfile.TemporaryDirectory() as d:
        install(d)
        rc, out = run(d, "add", "Lonely Mod", "--when", "spring")
        assert rc == 0 and "stays where it is" in out, out
        before = [l.strip()[1:] for l in io.open(os.path.join(
            d, "profiles", "Default", "modlist.txt"))][1:]
        run(d, "apply", "--season", "spring", tool="season.py")
        after = [l.strip()[1:] for l in io.open(os.path.join(
            d, "profiles", "Default", "modlist.txt"))][1:]
        assert before == after, "the modlist order changed"
    return "anchored on the mod under it; the order does not move"


@case
def t_events_can_be_made_used_and_removed():
    with tempfile.TemporaryDirectory() as d:
        install(d)
        rc, out = run(d, "event", "christmas", "12-24", "12-26")
        assert rc == 0, out
        rc, out = run(d, "add", "Winter Maps", "--when", "christmas")
        assert rc == 0, out
        t, e = table(d)
        assert e == {"christmas": ((12, 24), (12, 26))} and \
            t["Winter Maps"]["when"] == ("christmas",), (t, e)
        accepted(d)
        rc, out = run(d, "event", "christmas", "--remove")
        assert rc == 1 and "Winter Maps" in out, "removed an event a mod still uses"
        run(d, "remove", "Winter Maps")
        rc, out = run(d, "event", "christmas", "--remove")
        assert rc == 0 and table(d)[1] == {}, out
        rc, out = run(d, "event", "halloween", "13-01")
        assert rc == 1 and "month-day" in out, out
    return "made, scoped, refused while in use, removed; a bad date refused"


HAND = '''"""My config."""

# grass from the archive
LAYOUT = {}

TOGGLE_MODS = {
    # the snow, both winters
    "Winter Pack": {
        "seasons": ("winter", "winter_snow"),   # the old spelling
        "above": "Grass Compat",
    },
}
SOUND_SRC = None  # no ambience mod
PERIODS = {}
EVENTS = {}
'''


@case
def t_what_was_written_by_hand_is_kept():
    with tempfile.TemporaryDirectory() as d:
        install(d, config=HAND)
        rc, out = run(d, "add", "Map Pack", "--when", "summer")
        assert rc == 0, out
        new = config(d).split("\n")
        old = HAND.split("\n")
        # every line of the hand-written file, in order, and the new entry after it
        it = iter(new)
        missing = [l for l in old if not any(l == x for x in it)]
        assert not missing, "lost: %s" % missing
        assert io.open(os.path.join(d, "_tools", "seasons_config.py.bak"),
                       encoding="utf-8").read() == HAND, "the backup is not the old file"
        accepted(d)
    return "every hand-written line and comment kept, and the old file in .bak"


GHOUL = '''LAYOUT = {}
TOGGLE_MODS = {
    "Winter Pack": {
        "when": ("winter_snow",),
        "above": "Grass Compat",
    },"Map Pack": {
        "when": ("summer,spring"),
        "above": "Base Grass",
    },
}
SOUND_SRC = None
PERIODS = {}
EVENTS = {}
TOGGLE_MODS = {}
'''


@case
def t_a_ghoul_config_is_repaired_on_save():
    """The two mistakes from the Discord thread: the table thrown away by an empty one
    below it, and ("summer,spring")."""
    with tempfile.TemporaryDirectory() as d:
        install(d, config=GHOUL)
        rc, out = run(d, "status", tool="season.py")
        assert rc != 0, "the broken file was accepted as it is"
        rc, out = run(d, "list")
        assert "saving removes line" in out and "right shape" in out, out
        rc, out = run(d, "add", "Lonely Mod", "--when", "spring")
        assert rc == 0, out
        t, _ = table(d)
        assert t["Map Pack"]["when"] == ("summer", "spring"), t
        assert set(t) == {"Winter Pack", "Map Pack", "Lonely Mod"}, t
        assert config(d).count("TOGGLE_MODS =") == 1, "the empty table is still there"
        accepted(d)
    return "one TOGGLE_MODS left, (\"summer\", \"spring\"), and season.py accepts it"


@case
def t_a_file_python_cannot_read_is_left_alone():
    bad = HAND.replace('("winter", "winter_snow")', '(, "winter_snow")')
    with tempfile.TemporaryDirectory() as d:
        install(d, config=bad)
        rc, out = run(d, "add", "Map Pack", "--when", "summer")
        assert rc == 1 and "can't be edited here" in out and "line 9" in out, out
        assert config(d) == bad, "an unreadable file was overwritten"
    return "refused, with the line, and the file untouched"


@case
def t_the_window_edits_and_saves():
    """The window, driven the way a click would, in a process of its own."""
    driver = r'''
import sys
sys.path.insert(0, sys.argv[1])
import tkinter as tk
import config_edit as ce
import configure
root = tk.Tk()
root.withdraw()
cal, inst = ce.Calendar(), ce.Install()
app = configure.App(root, cal, inst)
app.select("Winter Pack")
app.set_when("Winter Pack", ["winter", "winter_snow"])
app.add_event("halloween", (10, 31), (10, 31))
app.select("Map Pack")
app.set_when("Map Pack", ["summer"])
app.set_when("Map Pack", [])
print("dirty before", cal.dirty())
print("saved", app.save(quiet=True))
print("dirty after", cal.dirty())
root.destroy()
'''
    with tempfile.TemporaryDirectory() as d:
        install(d)
        p = os.path.join(d, "drive.py")
        io.open(p, "w", encoding="utf-8").write(driver)
        r = subprocess.run([sys.executable, p, os.path.join(d, "_tools")], cwd=d,
                           capture_output=True, text=True)
        out = r.stdout + r.stderr
        assert r.returncode == 0 and "saved True" in out, out
        assert "dirty before True" in out and "dirty after False" in out, out
        t, e = table(d)
        assert set(t) == {"Winter Pack"}, "unticking everything did not take it off: %s" % t
        assert t["Winter Pack"] == {"when": ("winter", "winter_snow", "halloween"),
                                    "above": "Grass Compat"}, t
        assert e == {"halloween": ((10, 31), (10, 31))}, e
        accepted(d)
    return "ticks, a new event and an untick saved; season.py accepts the file"


@case
def t_the_window_deletes_an_event():
    """Deleting an event unticks it everywhere; a mod that had nothing else comes off the
    calendar rather than staying scoped to nothing."""
    driver = r'''
import sys
sys.path.insert(0, sys.argv[1])
import tkinter as tk
import config_edit as ce
import configure
root = tk.Tk()
root.withdraw()
cal, inst = ce.Calendar(), ce.Install()
app = configure.App(root, cal, inst)
app.select("Winter Pack")
app.set_when("Winter Pack", ["winter"])
app.add_event("halloween", (10, 31), (10, 31))
app.select("Map Pack")
app.set_when("Map Pack", ["halloween"])
print("before", sorted(cal.toggle), sorted(cal.events))
app.delete_event("halloween", ask=False)
print("saved", app.save(quiet=True))
root.destroy()
'''
    with tempfile.TemporaryDirectory() as d:
        install(d)
        p = os.path.join(d, "drive.py")
        io.open(p, "w", encoding="utf-8").write(driver)
        r = subprocess.run([sys.executable, p, os.path.join(d, "_tools")], cwd=d,
                           capture_output=True, text=True)
        out = r.stdout + r.stderr
        assert r.returncode == 0 and "saved True" in out, out
        assert "before ['Map Pack', 'Winter Pack'] ['halloween']" in out, out
        t, e = table(d)
        assert t == {"Winter Pack": {"when": ("winter",), "above": "Grass Compat"}}, t
        assert e == {}, e
        accepted(d)
    return "unticked on Winter Pack, Map Pack off the calendar, the event gone"


@case
def t_the_calendar_command_moves_and_turns_off_seasons():
    with tempfile.TemporaryDirectory() as d:
        install(d)
        game, tex = with_mod(d)
        rc, out = run(d, "calendar")
        assert rc == 0 and "Polesia's calendar" in out and "Late winter" in out, out
        rc, out = run(d, "calendar", "summer=5-1", "deep winter=11-15", "--only")
        assert rc == 0, out
        assert calendar_of(d) == {"summer": (5, 1), "winter_snow": (11, 15)}, calendar_of(d)
        assert "off: spring, autumn, winter, late winter" in out, out
        accepted(d)
        body = io.open(game, encoding="cp1251").read()
        assert "custom = true" in body and "summer = 5, 1" in body \
            and "winter_snow = 11, 15" in body and "autumn" not in body, body
        assert "dial = custom" in body and drawn(tex) == 32, (body, os.listdir(tex))
        rc, out = run(d, "calendar", "--on", "autumn")
        assert rc == 0 and calendar_of(d)["autumn"] == (9, 15), out
        rc, out = run(d, "calendar", "--off", "summer")
        assert rc == 0 and "summer" not in calendar_of(d), out
    return "moved, three off, handed to the game with a dial; --on and --off"


@case
def t_a_calendar_season_py_would_refuse_is_not_saved():
    with tempfile.TemporaryDirectory() as d:
        install(d)
        with_mod(d)
        run(d, "calendar", "summer=5-1")
        before = config(d)
        for args, says in ((["winter=11-25"], "winter would last 6 days"),
                           (["spring=2-29"], "February 29"),
                           (["summer=12-1"], "both start on Dec 1"),
                           (["summr=5-1"], "not a season"),
                           (["summer=5-41"], "not a date"),
                           (["--off", "spring", "summer", "autumn", "winter",
                             "winter_snow", "late_winter"], "every season off")):
            rc, out = run(d, "calendar", *args)
            assert rc == 1 and says in out, "%s: %s" % (args, out)
            assert config(d) == before, "%s changed the file" % args
    return "too short, Feb 29, a shared day, typos and no season at all: refused, unchanged"


@case
def t_the_reset_brings_polesia_back():
    with tempfile.TemporaryDirectory() as d:
        install(d)
        game, tex = with_mod(d)
        run(d, "calendar", "summer=5-1", "winter_snow=11-15", "--only")
        assert drawn(tex) == 32
        rc, out = run(d, "calendar", "--reset")
        assert rc == 0, out
        assert calendar_of(d) is None and "CALENDAR = None" in config(d), config(d)
        body = io.open(game, encoding="cp1251").read()
        assert "custom = false" in body and "dial = default" in body, body
        assert drawn(tex) == 0, "the redrawn dials were left behind"
        accepted(d)
    return "CALENDAR = None, the game back on Polesia's, the redrawn dials gone"


@case
def t_status_follows_the_calendar():
    """season.py runs on the calendar: one season on is the season all year, a mod scoped
    only to seasons that are off is named, and an MCM pin on one of them gives way."""
    with tempfile.TemporaryDirectory() as d:
        install(d)
        with_mod(d)
        run(d, "add", "Winter Pack", "--when", "winter")
        run(d, "calendar", "summer=1-1", "--only")
        ow = os.path.join(d, "overwrite", "gamedata", "configs")
        os.makedirs(ow)
        opts = os.path.join(ow, "axr_options.ltx")
        io.open(opts, "w").write("[mcm]\nseasons_zone/main/mode = spring\n")
        rc, out = run(d, "status", tool="season.py")
        assert rc == 0, out
        assert "season          summer" in out, out
        assert "your own: summer Jan 1" in out, out
        assert "Winter Pack is scoped only to winter, which your calendar has off" in out, out
        assert "MCM pins spring, which your calendar has off" in out, out
        io.open(opts, "w").write("[mcm]\nseasons_zone/main/mode = summer\n")
        rc, out = run(d, "status", tool="season.py")
        assert "(pinned in MCM)" in out and "has off" not in out.split("Winter Pack")[0], out
    return "summer all year, Winter Pack named, the spring pin set aside, a summer pin kept"


@case
def t_the_window_sets_the_calendar():
    driver = r'''
import sys
sys.path.insert(0, sys.argv[1])
import tkinter as tk
import config_edit as ce
import configure
root = tk.Tk()
root.withdraw()
cal, inst = ce.Calendar(), ce.Install()
app = configure.App(root, cal, inst)
app.set_when("Winter Maps", ["late_winter"])
app.use_dates(ce.meteorological())
app.srows["late_winter"][0].set(False)
app.dates_edited()
print("note", app.cal_note.cget("text").replace("\n", " "))
app.srows["summer"][2].set("")
app.dates_edited()
print("refused", app.save(quiet=True))
app.srows["summer"][2].set("1")
app.dates_edited()
print("saved", app.save(quiet=True))
print("dirty after", cal.dirty())
root.destroy()
'''
    with tempfile.TemporaryDirectory() as d:
        install(d)
        game, tex = with_mod(d)
        p = os.path.join(d, "drive.py")
        io.open(p, "w", encoding="utf-8").write(driver)
        r = subprocess.run([sys.executable, p, os.path.join(d, "_tools")], cwd=d,
                           capture_output=True, text=True)
        out = r.stdout + r.stderr
        assert r.returncode == 0 and "saved True" in out, out
        assert "refused False" in out, "saved with a blank day:\n" + out
        assert "never switched on: Winter Maps" in out, out
        assert "dirty after False" in out, out
        want = {"winter_snow": (12, 1), "spring": (4, 1), "summer": (6, 1),
                "autumn": (9, 1), "winter": (11, 1)}
        assert calendar_of(d) == want, calendar_of(d)
        accepted(d)
        body = io.open(game, encoding="cp1251").read()
        assert "custom = true" in body and "late_winter" not in body and drawn(tex) == 32, body
    return "meteorological dates, late winter off, a blank day refused; saved and drawn"


@case
def t_without_pillow_the_dial_is_hidden():
    """The game gets the dates and no dial, since the shipped one shows Polesia's. A PIL
    that will not import stands in for no Pillow, as a broken install would."""
    with tempfile.TemporaryDirectory() as d:
        install(d)
        game, tex = with_mod(d)
        block = os.path.join(d, "nopil", "PIL")
        os.makedirs(block)
        io.open(os.path.join(block, "__init__.py"), "w").write(
            "raise ImportError('no Pillow here')\n")
        env = dict(os.environ, PYTHONPATH=os.path.join(d, "nopil"))
        rc, out = run(d, "calendar", "summer=5-1", env=env)
        assert rc == 0 and "needs Pillow" in out, out
        body = io.open(game, encoding="cp1251").read()
        assert "custom = true" in body and "dial = none" in body and drawn(tex) == 0, body
        # status says what it would take, rather than promising a dial at the next launch
        rc, out = run(d, "status", tool="season.py", env=env)
        assert "dial            hidden" in out and "needs Pillow" in out, out
        # and the control: with Pillow the same kind of change is drawn
        rc, out = run(d, "calendar", "summer=5-2")
        body = io.open(game, encoding="cp1251").read()
        assert rc == 0 and "dial = custom" in body and drawn(tex) == 32, out + body
    return "dial = none and nothing drawn without it; drawn with it"


# --- what it must refuse, and what it must keep -------------------------------------------

PLAIN = """LAYOUT = {}
TOGGLE_MODS = {}
SOUND_SRC = None
PERIODS = {}
EVENTS = {}
"""


def raw_config(root, data, mode="wb"):
    with open(os.path.join(root, "_tools", "seasons_config.py"), mode) as f:
        f.write(data)


def raw_read(root):
    return open(os.path.join(root, "_tools", "seasons_config.py"), "rb").read()


@case
def t_a_file_keeps_its_encoding():
    """A cp1251 file with a coding line is Python's to read, and stays cp1251: its Cyrillic
    was saved as replacement characters."""
    text = ("# -*- coding: cp1251 -*-\n# \u0417\u0438\u043c\u043d\u0438\u0435 \u0442\u0435\u043a\u0441\u0442\u0443\u0440\u044b\n" + PLAIN)
    with tempfile.TemporaryDirectory() as d:
        install(d)
        raw_config(d, text.encode("cp1251"))
        rc, out = run(d, "add", "Map Pack", "--when", "summer")
        assert rc == 0, out
        data = raw_read(d)
        assert "\u0417\u0438\u043c\u043d\u0438\u0435".encode("cp1251") in data, "the Cyrillic was lost"
        assert b"\xef\xbf\xbd" not in data, "replacement characters written"
        accepted(d)
        # and without the coding line, where Python itself can't read it: refused, untouched
        raw_config(d, text.split("\n", 1)[1].encode("cp1251"))
        before = raw_read(d)
        rc, out = run(d, "add", "Lonely Mod", "--when", "spring")
        assert rc == 1 and "not saved as UTF-8" in out and raw_read(d) == before, out
    return "cp1251 kept; cp1251 without a coding line refused and left alone"


@case
def t_layouts_the_tool_cannot_edit_are_refused():
    for text, says in (
            (PLAIN.replace("TOGGLE_MODS = {}", 'TOGGLE_MODS = {}; SOUND_SRC = "Map Pack"'),
             "and another statement"),
            (PLAIN + 'TOGGLE_MODS["Map Pack"] = {"when": ("summer",), "above": "Base Grass"}\n',
             "changed after its table"),
            (PLAIN.replace("LAYOUT = {}\n", "") .replace("TOGGLE_MODS = {}",
                                                          "LAYOUT = TOGGLE_MODS = {}"),
             "and another name at once"),
            (PLAIN.replace("TOGGLE_MODS = {}", "if True:\n    TOGGLE_MODS = {}"),
             "in a way the tool can't edit")):
        with tempfile.TemporaryDirectory() as d:
            install(d, config=text)
            rc, out = run(d, "add", "Winter Pack", "--when", "winter")
            assert rc == 1 and says in out, "%r:\n%s" % (text, out)
            assert config(d) == text, "a refused file was changed"
    return "a shared line, a later entry, two names at once, an if: refused, untouched"


@case
def t_an_annotated_table_is_edited_where_it_is():
    text = PLAIN.replace("TOGGLE_MODS = {}", "TOGGLE_MODS: dict = {}").replace(
        "EVENTS = {}", "EVENTS: dict = {}")
    with tempfile.TemporaryDirectory() as d:
        install(d, config=text)
        rc, out = run(d, "add", "Winter Pack", "--when", "winter")
        assert rc == 0, out
        rc, out = run(d, "event", "xmas", "12-24", "12-26")
        assert rc == 0, out
        assert config(d).count("TOGGLE_MODS") == 1 and config(d).count("EVENTS") == 1, config(d)
        accepted(d)
    return "one TOGGLE_MODS and one EVENTS, both edited in place"


@case
def t_comments_the_user_wrote_are_kept():
    text = """LAYOUT = {}
TOGGLE_MODS = {
    "Winter Pack": {"when": ("winter",), "above": "Grass Compat"},
    # the maps and the overlay both come from the same author; keep them together
    "Map Pack": {"when": ("summer",), "above": "Base Grass"},
}
SOUND_SRC = None
PERIODS = {}
EVENTS = {}  # none yet
LATER = {
}
"""
    with tempfile.TemporaryDirectory() as d:
        install(d, config=text.replace("LATER = {\n}\n", ""))
        rc, out = run(d, "remove", "Map Pack")
        assert rc == 0, out
        assert "# the maps and the overlay" in config(d), "the comment above it went too"
        rc, out = run(d, "event", "xmas", "12-24")
        assert rc == 0 and "EVENTS = {  # none yet" in config(d), config(d)
        accepted(d)
    empty = PLAIN.replace("TOGGLE_MODS = {}", 'TOGGLE_MODS = {\n    # "Winter Maps": off until the patch\n}')
    with tempfile.TemporaryDirectory() as d:
        install(d, config=empty)
        rc, out = run(d, "add", "Winter Pack", "--when", "winter")
        assert rc == 0 and "# \"Winter Maps\": off until the patch" in config(d), config(d)
        accepted(d)
    return "a note above a removed entry, a note on an empty table, a commented-out entry"


@case
def t_odd_but_valid_layouts_are_edited():
    comma = PLAIN.replace("TOGGLE_MODS = {}", """TOGGLE_MODS = {
    "Winter Pack": {"when": ("winter",), "above": "Grass Compat"}
    ,
    "Map Pack": {"when": ("summer",), "above": "Base Grass"},
}""")
    for text in (comma, PLAIN.replace("\n", "\r"), comma.replace("\n", "\r")):
        with tempfile.TemporaryDirectory() as d:
            install(d)
            raw_config(d, text.encode("utf-8"))
            rc, out = run(d, "add", "Lonely Mod", "--when", "spring")
            assert rc == 0, "%r:\n%s" % (text[:60], out)
            accepted(d)
    return "a comma on its own line, and old Mac line ends"


@case
def t_a_broken_event_is_kept_until_it_is_fixed():
    text = PLAIN.replace("EVENTS = {}", 'EVENTS = {"fest": ((12, 24),)}')
    with tempfile.TemporaryDirectory() as d:
        install(d, config=text)
        rc, out = run(d, "add", "Winter Pack", "--when", "winter")
        assert rc == 1 and "EVENTS['fest']" in out and config(d) == text, out
        rc, out = run(d, "event", "fest", "--remove")
        assert rc == 0 and "fest" not in config(d), out
        rc, out = run(d, "add", "Winter Pack", "--when", "winter")
        assert rc == 0, out
    return "refused while it is there, not deleted behind your back; removable by name"


@case
def t_a_change_on_disk_is_not_written_over():
    sys.path.insert(0, HERE)
    import config_edit as ce
    with tempfile.TemporaryDirectory() as d:
        path = os.path.join(d, "seasons_config.py")
        io.open(path, "w", encoding="utf-8").write(PLAIN)
        cal = ce.Calendar(path)
        io.open(path, "a", encoding="utf-8").write("# edited by hand meanwhile\n")
        cal.events["xmas"] = ((12, 24), (12, 26))
        saved, lines = cal.save()
        assert not saved and "changed since it was read" in lines[0], lines
        assert io.open(path, encoding="utf-8").read().endswith("meanwhile\n")
        os.remove(path)
        saved, lines = cal.save()
        assert not saved and "changed since it was read" in lines[0], lines
    return "an edit made meanwhile, and a file deleted meanwhile: nothing written"


@case
def t_backups_the_tool_points_to_are_not_overwritten():
    sys.path.insert(0, HERE)
    import config_edit as ce
    with tempfile.TemporaryDirectory() as d:
        path = os.path.join(d, "seasons_config.py")
        io.open(path, "w", encoding="utf-8").write("TOGGLE_MODS = {,}\n")
        cal = ce.Calendar(path)
        kept = cal.start_over()
        cal.events["xmas"] = ((12, 24), (12, 26))
        assert cal.save()[0]
        cal.events["easter"] = ((4, 5), (4, 5))
        assert cal.save()[0]
        assert io.open(os.path.join(d, kept), encoding="utf-8").read() == "TOGGLE_MODS = {,}\n"
        # a save that can't keep a comment keeps a copy of its own
        io.open(path, "w", encoding="utf-8").write(
            PLAIN.replace("EVENTS = {}", "EVENTS = {\"a\": ((1, 1), (1, 2)),  # note\n"
                                         "          \"b\": ((2, 1), (2, 2))}"))
        cal = ce.Calendar(path)
        cal.events["c"] = ((3, 1), (3, 2))
        saved, lines = cal.save()
        name = [l for l in lines if "has them" in l][0].split(";")[1].split()[0]
        assert "# note" in io.open(os.path.join(d, name), encoding="utf-8").read(), lines
        cal.events["d"] = ((4, 1), (4, 2))
        assert cal.save()[0]
        assert "# note" in io.open(os.path.join(d, name), encoding="utf-8").read()
    return "the unreadable file and the one with the lost comment both survive later saves"


@case
def t_a_read_only_config_is_a_message():
    import stat
    with tempfile.TemporaryDirectory() as d:
        install(d, config=PLAIN)
        path = os.path.join(d, "_tools", "seasons_config.py")
        os.chmod(path, stat.S_IREAD)
        try:
            rc, out = run(d, "add", "Winter Pack", "--when", "winter")
            assert rc == 1 and "read-only" in out, out
            assert not os.path.exists(path + ".bak"), "wrote a .bak for a save that failed"
        finally:
            os.chmod(path, stat.S_IREAD | stat.S_IWRITE)
    return "refused before anything is written"


@case
def t_the_calendar_command_refuses_contradictions():
    with tempfile.TemporaryDirectory() as d:
        install(d)
        with_mod(d)
        for args, says in ((["summer=5-1", "--off", "summer"], "both moved and turned off"),
                           (["--on", "summer", "--off", "summer"], "both turned on and turned off"),
                           (["summer=5-1", "summer=6-1"], "given twice"),
                           (["--reset", "--preset", "met"], "give one"),
                           (["--preset", "met", "--only", "summer=5-1"], "give one")):
            rc, out = run(d, "calendar", *args)
            assert rc == 1 and says in out, "%s:\n%s" % (args, out)
        # a move written after --off is still a move
        rc, out = run(d, "calendar", "--off", "late_winter", "summer=5-2")
        assert rc == 0 and calendar_of(d).get("summer") == (5, 2), out
    return "five contradictions refused; a move after --off still counts"


@case
def t_a_broken_calendar_is_mended_from_its_own_dates():
    text = PLAIN + 'CALENDAR = {"summer": (5, 1), "winter": (5, 5)}  # oops, meant 11-5\n'
    with tempfile.TemporaryDirectory() as d:
        install(d, config=text)
        with_mod(d)
        rc, out = run(d, "add", "Winter Pack", "--when", "winter")
        assert rc == 1 and "would last 4 days" in out and config(d) == text, out
        rc, out = run(d, "calendar", "winter=11-5")
        assert rc == 0 and calendar_of(d) == {"summer": (5, 1), "winter": (11, 5)}, out
    return "not reset to Polesia's: summer May 1 stays, winter moves"


@case
def t_events_that_repeat_from_the_command_line():
    with tempfile.TemporaryDirectory() as d:
        install(d)
        for args in (["weekend", "--weekdays", "weekends"],
                     ["payday", "--days", "1", "15", "last"],
                     ["first_monday", "--weekdays", "monday", "--weeks", "first",
                      "--months", "dec", "jan"],
                     ["xmas_weekends", "--weekdays", "sat", "sun", "--between", "12-20",
                      "01-06"]):
            rc, out = run(d, "event", *args)
            assert rc == 0, out
        _, e = table(d)
        assert e == {"weekend": {"weekdays": ("sat", "sun")},
                     "payday": {"days": (1, 15, -1)},
                     "first_monday": {"weekdays": ("mon",), "weeks": (1,), "months": (12, 1)},
                     "xmas_weekends": {"weekdays": ("sat", "sun"),
                                       "within": ((12, 20), (1, 6))}}, e
        rc, out = run(d, "add", "Map Pack", "--when", "weekend")
        assert rc == 0, out
        accepted(d)
        for args, says in ((["fall", "10-1"], "another name for one"),
                           (["freezing", "1-1"], "a kind of weather"),
                           (["x", "--weeks", "first"], "'weeks' needs 'weekdays'"),
                           (["x", "--days", "31", "--months", "feb"], "never happens"),
                           (["x", "12-24", "--weekdays", "sat"], "--between"),
                           (["x", "--weekdays", "funday"], "days of the week")):
            rc, out = run(d, "event", *args)
            assert rc == 1 and says in out, "%s:\n%s" % (args, out)
    return "four rules saved as written; six mistakes refused"


@case
def t_seasons_can_be_named():
    with tempfile.TemporaryDirectory() as d:
        install(d)
        game, tex = with_mod(d)
        rc, out = run(d, "name", "deep winter", "The Long Cold")
        assert rc == 0 and "drawn for your calendar" in out, out
        ns = {}
        exec(config(d), ns)
        assert ns["NAMES"] == {"winter_snow": "The Long Cold"}, ns.get("NAMES")
        assert "name_winter_snow = The Long Cold" in io.open(game, encoding="cp1251").read()
        for args, says in ((["summer", "x" * 21], "21 characters"),
                           (["summer", "Winter"], "would both be called"),
                           (["summr", "Hot"], "not a season")):
            rc, out = run(d, "name", *args)
            assert rc == 1 and says in out, "%s:\n%s" % (args, out)
        rc, out = run(d, "name", "deep winter", "--reset")
        assert rc == 0 and "NAMES = None" in config(d), out
        assert "custom = false" in io.open(game, encoding="cp1251").read()
        assert drawn(tex) == 0
    return "named, drawn and handed on; three bad names refused; reset clears it all"


@case
def t_presets_save_and_load():
    with tempfile.TemporaryDirectory() as d:
        install(d)
        with_mod(d)
        run(d, "event", "weekend", "--weekdays", "weekends")
        run(d, "add", "Winter Pack", "--when", "winter", "weekend")
        run(d, "add", "Lonely Mod", "--when", "spring")
        run(d, "calendar", "summer=5-1", "--off", "late_winter")
        run(d, "name", "deep winter", "The Long Cold")
        rc, out = run(d, "preset", "save", "Mine", "--about", "a test")
        assert rc == 0 and "calendar and season names, events and periods, mods on the " \
            "calendar" in out and "texture" not in out, out
        preset = open(os.path.join(d, "_tools", "presets", "Mine.json"), encoding="utf-8").read()
        # another install: Lonely Mod is not there, and Grass Compat - Winter Pack's anchor -
        # is not either
        other = [m for m in MODS if m[0] not in ("Lonely Mod", "Grass Compat")]
        with tempfile.TemporaryDirectory() as e:
            install(e, mods=other)
            with_mod(e)
            os.makedirs(os.path.join(e, "_tools", "presets"))
            io.open(os.path.join(e, "_tools", "presets", "Mine.json"), "w",
                    encoding="utf-8").write(preset)
            rc, out = run(e, "preset", "load", "mine")
            assert rc == 0, out
            assert "not installed here, left out: Lonely Mod" in out, out
            assert "Winter Pack (now above" in out, out
            t, ev = table(e)
            assert set(t) == {"Winter Pack"} and t["Winter Pack"]["above"] != "Grass Compat", t
            assert ev == {"weekend": {"weekdays": ("sat", "sun")}}, ev
            assert calendar_of(e)["summer"] == (5, 1) and "late_winter" not in calendar_of(e)
            accepted(e)
            # only the calendar, from the same preset, into a fresh file
            os.remove(os.path.join(e, "_tools", "seasons_config.py"))
            rc, out = run(e, "preset", "load", "Mine", "--parts", "calendar")
            assert rc == 0 and table(e) == ({}, {}), out
        # a preset that would break the config is refused whole
        bad = os.path.join(d, "_tools", "presets", "Bad.json")
        io.open(bad, "w", encoding="utf-8").write(
            '{"seasons_of_the_zone_preset": 1, "calendar": {"summer": [5, 1], "winter": [5, 5]}}')
        rc, out = run(d, "preset", "load", "Bad")
        assert rc == 1 and "can't be used" in out and "4 days" in out, out
        shipped = os.path.join(d, "_tools", "presets", "Shipped.json")
        io.open(shipped, "w", encoding="utf-8").write(
            '{"seasons_of_the_zone_preset": 1, "shipped": true, "calendar": null}')
        rc, out = run(d, "preset", "save", "shipped", "--force")
        assert rc == 1 and "comes with the tool" in out, out
    return "saved with its parts; loaded elsewhere, missing mods left out and re-anchored"


@case
def t_the_window_names_seasons_and_holds_bad_days():
    driver = r"""
import sys
sys.path.insert(0, sys.argv[1])
import tkinter as tk
import config_edit as ce
import configure
root = tk.Tk()
root.withdraw()
cal, inst = ce.Calendar(), ce.Install()
app = configure.App(root, cal, inst)
app.srows["winter_snow"][7].set("The Long Cold")
app.names_edited()
app.srows["summer"][2].set("1_0")
app.dates_edited()
print("refused", app.save(quiet=True), app.bad_dates)
app.srows["summer"][2].set("20")
app.dates_edited()
app.add_event("weekend", spec={"weekdays": ("sat", "sun")})
print("saved", app.save(quiet=True))
print("names", cal.names)
root.destroy()
"""
    with tempfile.TemporaryDirectory() as d:
        mods = MODS + [("Map Pack", True, [])]          # MO2 lists Map Pack twice
        install(d, mods=mods)
        with_mod(d)
        p = os.path.join(d, "drive.py")
        io.open(p, "w", encoding="utf-8").write(driver)
        r = subprocess.run([sys.executable, "-B", p, os.path.join(d, "_tools")], cwd=d,
                           capture_output=True, text=True)
        out = r.stdout + r.stderr
        assert r.returncode == 0 and "refused False ['Summer']" in out, out
        assert "saved True" in out and "{'winter_snow': 'The Long Cold'}" in out, out
        ns = {}
        exec(config(d), ns)
        assert ns["NAMES"] == {"winter_snow": "The Long Cold"}, ns.get("NAMES")
        assert ns["EVENTS"] == {"weekend": {"weekdays": ("sat", "sun")}}, ns["EVENTS"]
        accepted(d)
    return "a name, a rule event, and a day box that holds 1_0 refused"


@case
def t_a_real_config_comes_back_unchanged():
    """The live install's config, loaded and written back with nothing changed."""
    live = os.path.join(os.environ.get("GAMMA_INSTALL", r"D:\GAMMA"), "_tools",
                        "seasons_config.py")
    if not os.path.isfile(live):
        return "no live config here - skipped"
    sys.path.insert(0, HERE)
    import config_edit as ce
    cal = ce.Calendar(live)
    assert not cal.error and not cal.dirty(), (cal.error, cal.fixes)
    text, kept = cal.render()
    data = ((b"\xef\xbb\xbf" if cal.bom else b"")
            + text.replace("\n", cal.nl).encode(cal.encoding))
    assert kept and data == cal.original, "a no-op save changes it"
    return "%d entries, byte for byte" % len(cal.toggle)


if __name__ == "__main__":
    print("  running the shipped configure.py against scratch installs")
    bad = 0
    for fn in CASES:
        try:
            print("  PASS  %-48s %s" % (fn.__name__[2:], fn()))
        except AssertionError as e:
            bad += 1
            print("  FAIL  %-48s %s" % (fn.__name__[2:], e))
        except Exception as e:
            bad += 1
            print("  ERROR %-48s %s: %s" % (fn.__name__[2:], type(e).__name__, e))
    print("\n  %d/%d passed" % (len(CASES) - bad, len(CASES)))
    sys.exit(1 if bad else 0)
