"""Run the SHIPPED `season.py whowins` against a small Mod Organizer install.

whowins is how a seasonal mod gets its `above`. The answer it must never give is the mod
being placed: anchored above itself, a mod stays where it is, and the next mod to ship
the same file above it wins without a word. That is the easy mistake, because MO2
enables a freshly installed mod at the top of the list, so the mod asked about is often
the one winning the file. Each case builds a scratch install and runs season.py as a
user would.

  python _tools/test_whowins.py
"""
import io
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
FILE = "shaders/r3/settings_screenspace_TERRAIN.h"
CRLF = "\r\n"


def install(root, mods, config=None):
    """mods: [(name, enabled, ships FILE)], highest priority first, as modlist.txt lists
    them."""
    os.makedirs(os.path.join(root, "_tools"))
    shutil.copy2(os.path.join(HERE, "season.py"), os.path.join(root, "_tools", "season.py"))
    if config is not None:
        io.open(os.path.join(root, "_tools", "seasons_config.py"), "w",
                encoding="utf-8").write(config)
    io.open(os.path.join(root, "ModOrganizer.ini"), "w", encoding="utf-8").write(
        "[General]" + CRLF + "selected_profile=@ByteArray(Default)" + CRLF)
    prof = os.path.join(root, "profiles", "Default")
    os.makedirs(prof)
    lines = ["# This file was automatically generated by Mod Organizer."]
    for name, on, ships in mods:
        lines.append(("+" if on else "-") + name)
        d = os.path.join(root, "mods", name, "gamedata", *FILE.split("/")[:-1])
        os.makedirs(d)
        if ships:
            io.open(os.path.join(d, FILE.split("/")[-1]), "w").write("// " + name)
    io.open(os.path.join(prof, "modlist.txt"), "w", encoding="utf-8",
            newline="").write(CRLF.join(lines) + CRLF)


def run(root, *args):
    r = subprocess.run([sys.executable, os.path.join(root, "_tools", "season.py")] +
                       list(args), capture_output=True, text=True, cwd=root)
    return r.returncode, r.stdout + r.stderr


def answers(out):
    """Every `"above": "..."` the output offers, in order."""
    return [l.split('"above": "', 1)[1].rstrip('"') for l in out.splitlines()
            if '"above": "' in l]


# The shape of the Discord report: INVERNO freshly installed, enabled, on top.
ON_TOP = [("INVERNO", True, True), ("SSS 24", True, True), ("SSS 23", False, True),
          ("Seasons of the Zone", True, False)]

CASES = []


def case(fn):
    CASES.append(fn)
    return fn


@case
def t_for_leaves_your_mod_out():
    with tempfile.TemporaryDirectory() as d:
        install(d, ON_TOP)
        rc, out = run(d, "whowins", FILE, "--for", "INVERNO")
        assert rc == 0, out
        assert answers(out) == ["SSS 24"], "answered %s" % answers(out)
        assert "<-- yours" in out and "<-- to outrank" in out, out
    return "INVERNO on top, --for INVERNO answers SSS 24 and only that"


@case
def t_without_for_the_next_one_down_is_named():
    with tempfile.TemporaryDirectory() as d:
        install(d, ON_TOP)
        rc, out = run(d, "whowins", FILE)
        assert rc == 0, out
        # the top enabled mod is still the plain answer; the one under it is offered for
        # the case where the top one is yours
        assert answers(out) == ["INVERNO", "SSS 24"], "answered %s" % answers(out)
        assert "--for" in out, "no pointer to --for"
    return "INVERNO first, then SSS 24 as the answer if INVERNO is yours"


@case
def t_a_disabled_mod_never_wins():
    with tempfile.TemporaryDirectory() as d:
        install(d, [("INVERNO", False, True)] + ON_TOP[1:])
        rc, out = run(d, "whowins", FILE)
        assert rc == 0, out
        assert answers(out)[0] == "SSS 24", "answered %s" % answers(out)
    return "a disabled INVERNO on top is skipped"


@case
def t_nothing_else_ships_it():
    with tempfile.TemporaryDirectory() as d:
        install(d, [("INVERNO", True, True), ("Seasons of the Zone", True, False)])
        rc, out = run(d, "whowins", FILE, "--for", "INVERNO")
        assert rc == 0, out
        assert not answers(out), "answered %s" % answers(out)
        assert "any anchor keeps INVERNO winning" in out, out
    return "sole shipper: no anchor needed, and it says so"


@case
def t_a_mod_that_does_not_ship_the_file_is_refused():
    with tempfile.TemporaryDirectory() as d:
        install(d, ON_TOP)
        rc, out = run(d, "whowins", FILE, "--for", "Seasons of the Zone")
        assert rc == 1, "exit %d" % rc
        assert "does not ship this file" in out, out
        assert not answers(out), "answered %s" % answers(out)
    return "exit 1 and no answer"


@case
def t_a_name_mo2_does_not_have_is_refused():
    with tempfile.TemporaryDirectory() as d:
        install(d, ON_TOP)
        rc, out = run(d, "whowins", FILE, "--for", "Project_I.N.V.E.R.N.O")
        assert rc == 1, "exit %d" % rc
        assert "exactly as MO2 shows it" in out, out
    return "exit 1, pointing at MO2's name"


@case
def t_a_half_written_config_does_not_block_it():
    """whowins is how the config gets its `above`, so a config that is not finished yet
    must not stop it. The control: status refuses the same config."""
    bad = 'TOGGLE_MODS = {"INVERNO": {"when": ("winter"), "above": ""}}\n'
    with tempfile.TemporaryDirectory() as d:
        install(d, ON_TOP, config=bad)
        rc, out = run(d, "whowins", FILE, "--for", "INVERNO")
        assert rc == 0 and answers(out) == ["SSS 24"], (rc, out)
        rc, out = run(d, "status")
        assert rc != 0 and "needs fixing" in out, "status accepted a broken config"
    return "whowins answers; status still refuses the config"


if __name__ == "__main__":
    print("  running the shipped whowins against scratch installs")
    bad = 0
    for fn in CASES:
        try:
            print("  PASS  %-46s %s" % (fn.__name__[2:], fn()))
        except AssertionError as e:
            bad += 1
            print("  FAIL  %-46s %s" % (fn.__name__[2:], e))
        except Exception as e:
            bad += 1
            print("  ERROR %-46s %s: %s" % (fn.__name__[2:], type(e).__name__, e))
    print("\n  %d/%d passed" % (len(CASES) - bad, len(CASES)))
    sys.exit(1 if bad else 0)
