"""Your calendar on the PDA: the player's own seasons, events, periods and spells reach the
game, whose Year page heads with the season the world runs and says why, lists what is on
and what is coming, draws the player's own over the grid, and glows what is on. A PDA
message goes out for each of them that MCM's Your calendar page leaves on, at the start and
as one begins while playing; a turn drawing near and coming is told while playing; with the
dice on, no message promises the next season.

The game side runs under LuaJIT through test_calendar's harness, on calendar files written
by season.py's own writer, so the two sides are checked against each other rather than
against a copy of the format.

  python _tools/test_your_calendar.py
"""
import datetime
import io
import os
import re
import shutil
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.dont_write_bytecode = True
import season                                                   # noqa: E402
import build_release                                            # noqa: E402
import test_calendar as tcal                                    # noqa: E402
import test_configure as tc                                     # noqa: E402

CASES = []
CRLF = "\r\n"
PAGE = io.open(os.path.join(tcal.SCRIPTS, "ui_seasons_pda.script"), encoding="utf-8").read()
OVER_H = int(re.search(r"local OVER_H\s*=\s*(\d+)", PAGE).group(1))
HALO_H = int(re.search(r"local HALO_H\s*=\s*(\d+)", PAGE).group(1))
CELL_H, PITCH, ROW_Y0, GUT, CELL_W = tcal.CELL_H, tcal.PITCH, tcal.ROW_Y0, tcal.GUT, tcal.CELL_W


def case(fn):
    CASES.append(fn)
    return fn


# One of each, and two kinds of event rule. Saturday 17 October 2026 is in autumn, inside
# Hunter's moon and a weekend, two weeks before Halloween and the turn to winter.
OWN = {"Hunter's moon": ((10, 10), (10, 31)), "Wormhole season": ((8, 1), (8, 31))}
EVENTS = {"christmas": ((12, 24), (12, 26)), "halloween": ((10, 31), (10, 31)),
          "weekend": {"weekdays": ("sat", "sun")}, "twelvetide": ((12, 26), (1, 6))}
PERIODS = {"high_summer": (7, 1)}
SPELLS = {"Indian summer": {"in": ("autumn",), "chance": 2, "days": (2, 4), "as": "summer"},
          "Odd fog": {"in": ("autumn", "Hunter's moon"), "chance": 0.5, "days": 1,
                      "as": None}}


def tables(own=OWN, events=EVENTS, periods=PERIODS, spells=SPELLS):
    """season.py's tables set to these for a `with`, and put back after"""
    class Swap(object):
        def __enter__(self):
            self.saved = (season.OWN_SEASONS, season.EVENTS, season.PERIODS, season.SPELLS)
            season.OWN_SEASONS, season.EVENTS = own, events
            season.PERIODS, season.SPELLS = periods, spells
            return season

        def __exit__(self, *a):
            (season.OWN_SEASONS, season.EVENTS, season.PERIODS,
             season.SPELLS) = self.saved
    return Swap()


def calendar(today=None, spell=None, roll=None, **kw):
    """season_calendar.ltx as season.py writes it, Polesia's calendar and the player's own
    from `kw` (the tables above unless given): with `spell`, (season, name, first, last),
    its [spell]; `roll`, (season, draw, chance), its [roll]; and `today`, (day,
    [(name, first, last, as)], [weather kinds]), its [today]. Returns the text and
    season.py's keys."""
    with tables(**kw) as s:
        lines = ["; generated by _tools/season.py from seasons_config.py - do not edit by hand",
                 "[calendar]", "custom = false", "dial = default"] + s.your_sections()
        keys = s.your_keys()
    if spell:
        lines += ["", "[spell]", "season = %s" % spell[0], "name = %s" % spell[1],
                  "first = %s" % spell[2], "last = %s" % spell[3]]
    if roll:
        lines += ["", "[roll]", "season = %s" % roll[0], "draw = %d" % roll[1],
                  "chance = %d" % roll[2], "day = 2026-10-17"]
    if today:
        day, on, weather = today
        lines += ["", "[today]", "day = %s" % day]
        if weather:
            lines.append("weather = %s" % ", ".join(weather))
        for i, (name, first, last, brings) in enumerate(on, 1):
            lines += ["%d_spell = %s" % (i, name), "%d_key = %s" % (i, keys[("spell", name)]),
                      "%d_first = %s" % (i, first), "%d_last = %s" % (i, last)]
            if brings:
                lines.append("%d_as = %s" % (i, brings))
    return CRLF.join(lines) + CRLF, keys


ROW_SETUP = """
function make_rows(p, n1, n2, heads)
    p.heads = {}
    for i = 1, heads do p.heads[i] = mkwidget() end
    p.rows, p.used, p.cursor = {}, {}, {}
    for col = 1, 2 do
        p.rows[col] = {}
        for i = 1, (col == 1 and n1 or n2) do
            p.rows[col][i] = {mkwidget(), mkwidget(), mkwidget()}
        end
        p.used[col], p.cursor[col] = 0, 0
    end
    p.head_n = 0
end
"""


def filled(lua, g):
    """The page's Fill(), with every widget it writes to, as InitControls makes them. Returns
    the page, and what it shows: {"header", "status", "rows": [(col, [texts], rgb, glows)],
    "heads": [texts]}."""
    lua.execute(ROW_SETUP)
    bars = lua.table_from([g.mkwidget() for _ in range(tcal.BAR_POOL)])
    axis = lua.table_from([g.mkwidget() for _ in range(5)])
    months = lua.table_from([g.mkwidget() for _ in range(12)])
    p = g.make_page(g.SeasonsPDA, bars, axis, months)
    for name in ("header", "bar", "subheader", "turning", "dial", "dial_caption",
                 "grid_cap_l", "grid_cap_r"):
        p[name] = g.mkwidget()
    g.make_rows(p, 12, 12, 4)
    g.SeasonsPDA.Fill(p)
    # a Lua table crosses into Python as a new wrapper each time, so whether a widget is
    # on the glow list is asked on the Lua side
    glows = lua.eval("function(p, w) for _, x in ipairs(p.glow or {}) do "
                     "if rawequal(x, w) then return true end end return false end")
    rows = []
    for col in (1, 2):
        for i in range(1, 13):
            s = p.rows[col][i]
            ws = [s[f] for f in (1, 2, 3) if s[f].vis]
            if ws:
                c = ws[0].col
                rows.append((col, [w.text for w in ws], (c["r"], c["g"], c["b"]),
                             any(glows(p, w) for w in ws)))
    heads = [p.heads[i].text for i in range(1, 5) if p.heads[i].vis]
    return p, {"header": p.header.text, "status": p.turning.text, "rows": rows,
               "heads": heads, "status_glows": glows(p, p.turning), "bar": p.bar.tex}


def page_data(day=(2026, 10, 17), mcm=None, **kw):
    text, keys = calendar(**kw)
    lua, g = tcal.build(*day, calendar=text, mcm=mcm)
    return lua, g, g.zzz_seasons_of_the_zone.calendar_page(), keys


def items(t):
    return [t[i] for i in range(1, len(t) + 1)] if t else []


@case
def t_the_page_says_what_is_on_and_what_is_coming():
    """17 October: Hunter's moon and a weekend are on, each to its last day; coming up, the
    next of everything soonest first, the turn to winter among them, plain while nothing
    fixes the season."""
    lua, g, d, keys = page_data()
    now = [(r.kind, r.show, r.when, r.what) for r in items(d.now)]
    assert now == [("own", "Hunter's moon", "until Oct 31", "A season of your own"),
                   ("event", "Weekend", "until Oct 18", "An event of yours")], now
    coming = [(r.date, r.when, r.what) for r in items(d.coming)][:7]
    assert coming == [("Oct 31", "in 14 days", "Halloween"),
                      ("Nov 1", "in 15 days", "Winter"),
                      ("Nov 20", "in 34 days", "Storm. Artefacts surface."),
                      ("Dec 14", "in 58 days", "Clear sky. The Zone goes quiet."),
                      ("Dec 24", "in 68 days", "Christmas"),
                      ("Dec 26", "in 70 days", "Twelvetide"),
                      ("Mar 20", "in 154 days", "Storm. Artefacts surface.")], coming
    later = [r.what for r in items(d.coming)]
    assert "High summer begins" in later and "Wormhole season begins" in later, later
    assert "Weekend" not in later and "Hunter's moon begins" not in later, \
        "something on today is listed as coming"
    # the next Saturday, a week off, is how a weekend shows the day after it ends
    _, _, d2, _ = page_data(day=(2026, 10, 19))
    wk = [(r.date, r.what) for r in items(d2.coming) if r.what == "Weekend"]
    assert wk == [("Oct 24", "Weekend")], wk
    return "2 on, each to its last day; %d coming, Halloween then the turn to winter" % len(
        later)


@case
def t_the_grid_draws_the_player_s_own_and_glows_what_is_on():
    """A line over the days of each season of the player's own, dated event and period:
    Hunter's moon on, glowing over a halo; the rest dim. Weekly rules are not drawn."""
    lua, g, d, _ = page_data()
    marks = sorted((m["from"], m["to"], bool(m.active)) for m in items(d.marks))
    doy = lambda m, dd: datetime.date(2026, m, dd).timetuple().tm_yday  # noqa: E731
    want = sorted([(doy(10, 10), doy(10, 31), True), (doy(8, 1), doy(8, 31), False),
                   (doy(12, 24), doy(12, 26), False), (doy(10, 31), doy(10, 31), False),
                   (doy(12, 26), 365, False), (1, doy(1, 6), False),
                   (doy(7, 1), doy(9, 14), False)])
    assert marks == want, marks
    p, shown = filled(lua, g)
    bars = [p.bars[i] for i in range(1, tcal.BAR_POOL + 1) if p.bars[i].vis]
    lines = [b for b in bars if int(b.h) == OVER_H]
    lit = [p.glow_bars[i] for i in range(1, len(p.glow_bars) + 1)]
    halos = [p.halos[i] for i in range(1, len(p.halos) + 1)]
    # Hunter's moon is one run in October; its line sits in the gap above the row
    assert len(lit) == 1 and len(halos) == 1, (len(lit), len(halos))
    oct_y = ROW_Y0 + 9 * PITCH
    assert (int(lit[0].x), int(lit[0].y), int(lit[0].w)) == (
        GUT + 9 * CELL_W, oct_y - 3, 22 * CELL_W - 1), (lit[0].x, lit[0].y, lit[0].w)
    assert int(halos[0].h) == HALO_H and int(halos[0].y) == oct_y - HALO_H
    # a line for each month a window touches: Aug, Oct twice, Dec, Jan, Jul to Sep
    assert len(lines) == 9, len(lines)
    assert all(int(b.y) % PITCH == (ROW_Y0 - 3) % PITCH for b in lines), \
        "a line is not in the gap above a row"
    # the glow moves: two moments, two colours, on the line and the rows that are on
    cols = []
    for ms in (0, 500):
        g.time_global = lambda ms=ms: ms
        g.SeasonsPDA.Update(p)
        cols.append((lit[0].col["r"], lit[0].col["g"], lit[0].col["b"], halos[0].col["a"]))
    assert cols[0] != cols[1], "the glow stands still: %s" % cols
    return "7 spans, Hunter's moon lit over a halo, 9 lines in the gaps; the glow moves"


@case
def t_the_page_lists_now_coming_the_year_and_its_spells():
    """What the player reads: Now glowing, Coming up, the seasons with the period after
    summer, and the spells that can start in autumn with their odds a day."""
    lua, g, _, _ = page_data()
    p, shown = filled(lua, g)
    assert shown["heads"] == ["Now", "Coming up", "Season starts", "Spells in autumn"], \
        shown["heads"]
    left = [(r[1], r[3]) for r in shown["rows"] if r[0] == 1]
    assert left[:2] == [(["Hunter's moon", "until Oct 31", "A season of your own"], True),
                        (["Weekend", "until Oct 18", "An event of yours"], True)], left[:2]
    assert left[2] == (["Oct 31", "in 14 days", "Halloween"], False), left[2]
    right = [r[1] for r in shown["rows"] if r[0] == 2]
    assert right[:8] == [["Spring", "from Apr 15"], ["Summer", "from May 20"],
                         ["High summer", "from Jul 1"], ["Autumn", "from Sep 15"],
                         ["Winter", "from Nov 1"], ["Deep winter", "from Dec 1"],
                         ["Late winter", "from Mar 5"], ["Indian summer", "2% a day"]], right
    assert len(right) == 9 and right[8] == ["Odd fog", "0.5% a day"], right
    assert shown["header"] == "Autumn in the Zone" and shown["status"] == "Winter in 15 days.", \
        (shown["header"], shown["status"])
    return "Now 2 glowing, Coming up %d, the year with its period, 2 spells" % (
        len(left) - 2)


@case
def t_the_season_running_heads_the_page_and_says_why():
    """A pin, the dice and a spell each head the page with their season and its bar, say
    why beside what the calendar reads, and glow; with the dice on and nothing rolled, the
    page promises no next season."""
    got = {}
    pin = {"seasons_zone/main/mode": "winter_snow"}
    cases = {"pinned": dict(mcm=pin),
             "rolled": dict(roll=("winter", 5, 25)),
             "spell": dict(spell=("summer", "Indian summer", "2026-10-16", "2026-10-19"),
                           today=("2026-10-17", [("Indian summer", "2026-10-16", "2026-10-19",
                                                  "summer")], [])),
             "dice": dict(mcm={"seasons_zone/main/dice": True})}
    for name, kw in cases.items():
        lua, g, d, _ = page_data(**kw)
        p, shown = filled(lua, g)
        got[name] = (shown["header"], shown["status"], shown["bar"],
                     shown["status_glows"])
    assert got == {
        "pinned": ("Deep winter in the Zone", "Pinned. The calendar reads autumn.",
                   "ui_season_hdr_winter_snow", True),
        "rolled": ("Winter in the Zone", "By the dice. The calendar reads autumn.",
                   "ui_season_hdr_winter", True),
        "spell": ("Summer in the Zone",
                  "Indian summer, until Oct 19. The calendar reads autumn.",
                  "ui_season_hdr_summer", True),
        "dice": ("Autumn in the Zone", "The dice roll again at the next launch.",
                 "ui_season_hdr_autumn", False)}, got
    # The page is kept between openings: with the pin taken off, the next opening's status
    # line is white and still, not left in the glow's last colour
    pin_now = dict(pin)
    lua, g, d, _ = page_data(mcm=pin_now)
    p, shown = filled(lua, g)
    g.time_global = lambda: 700
    g.SeasonsPDA.Update(p)
    glowed = (p.turning.col["r"], p.turning.col["g"], p.turning.col["b"])
    pin_now.clear()
    g.SeasonsPDA.Fill(p)
    g.SeasonsPDA.Update(p)
    after = (p.turning.col["r"], p.turning.col["g"], p.turning.col["b"])
    assert glowed != (255, 255, 255) and after == (255, 255, 255), (glowed, after)
    assert p.turning.text == "Winter in 15 days.", p.turning.text
    # and the running season's row in the year list glows, the calendar's stays white
    lua, g, d, _ = page_data(roll=("winter", 5, 25))
    p, shown = filled(lua, g)
    rows = {r[1][0]: (r[2], r[3]) for r in shown["rows"] if r[0] == 2}
    assert rows["Winter"][1] and not rows["Autumn"][1] and rows["Autumn"][0] == (255, 255, 255)
    return "pin, dice and spell each say why and glow; the dice alone promise nothing"


@case
def t_a_spell_tints_its_days_and_the_marked_days_follow_their_switches():
    """A spell that brings summer tints its four days summer's color and is on the Now
    list with the season it brings; an anniversary with its storm off says only what is
    left, and one with every switch off is not marked at all."""
    spell = dict(spell=("summer", "Indian summer", "2026-10-16", "2026-10-19"),
                 today=("2026-10-17", [("Indian summer", "2026-10-16", "2026-10-19",
                                        "summer")], ["freezing"]))
    lua, g, d, _ = page_data(**spell)
    now = [(r.kind, r.show, r.when, r.what) for r in items(d.now)]
    assert ("spell", "Indian summer", "until Oct 19", "Brings summer") in now, now
    assert ("weather", "Freezing", "today", "A night below zero") in now, now
    tints = [(t["from"], t["to"], t.season) for t in items(d.tints)]
    assert tints == [(289, 292, "summer")], tints
    bars, _, _, page, _ = tcal.draw(lua, g)
    summer = tuple(int(v) for v in re.search(r"summer\s*=\s*\{([^}]+)\}", PAGE)
                   .group(1).split(","))
    tinted = [b for b in bars if b["h"] == CELL_H and b["rgb"] == summer
              and b["y"] == ROW_Y0 + 9 * PITCH]
    assert tinted and tinted[-1]["x"] == GUT + 15 * CELL_W and \
        tinted[-1]["w"] == 4 * CELL_W - 1, tinted
    # the weather kind is the staged day's only
    _, _, d2, _ = page_data(day=(2026, 10, 18), **spell)
    assert not [r for r in items(d2.now) if r.kind == "weather"], "yesterday's frost"

    off = {"seasons_zone/main/rem_ann_weather": False}
    _, _, d, _ = page_data(day=(2026, 10, 2), mcm=off)
    now = [(r.kind, r.what) for r in items(d.now)]
    assert now[0] == ("marked", "Artefacts surface. Voices on the PDA."), now
    silent = dict(off, **{"seasons_zone/main/rem_ann_artefacts": False,
                          "seasons_zone/main/rem_anniversary": False})
    lua, g, d, _ = page_data(day=(2026, 10, 2), mcm=silent)
    assert d.marked is None and not [r for r in items(d.now) if r.kind == "marked"]
    # the API still says what day it is: other mods read it by the date
    assert d.marked_day is not None and d.marked_day.key == "cop", d.marked_day
    bars, _, _, _, _ = tcal.draw(lua, g)
    assert len([b for b in bars if b["h"] == tcal.MARK_H]) == 2, "anniversaries underlined"
    coming = [r.what for r in items(d.coming) if r.kind == "marked"]
    assert len(coming) == 2, coming
    return "Indian summer tints Oct 16-19; storm off says the rest; all off unmarks the four"


@case
def t_a_spell_taken_out_since_launch_leaves_the_page():
    """configure.bat takes a spell out after play.bat staged it: the page leaves it off,
    unless it is the spell whose season the game still follows until the next launch."""
    staged = CRLF.join(["", "[today]", "day = 2026-10-17", "1_spell = Gone spell",
                        "1_key = spell_gone_spell", "1_first = 2026-10-16",
                        "1_last = 2026-10-19"]) + CRLF
    text, _ = calendar(spells={})
    lua, g = tcal.build(2026, 10, 17, calendar=text + staged)
    d = g.zzz_seasons_of_the_zone.calendar_page()
    assert not [r for r in items(d.now) if r.kind == "spell"], "a spell taken out is on"
    assert not [m for m in items(d.marks) if m["from"] == 289], "its days are still drawn"
    in_force = CRLF.join(["", "[spell]", "season = summer", "name = Gone spell",
                          "first = 2026-10-16", "last = 2026-10-19"]) + CRLF
    lua, g = tcal.build(2026, 10, 17, calendar=text + in_force + staged.replace(
        "1_last = 2026-10-19", "1_last = 2026-10-19" + CRLF + "1_as = summer"))
    d = g.zzz_seasons_of_the_zone.calendar_page()
    now = [(r.show, r.what) for r in items(d.now) if r.kind == "spell"]
    assert now == [("Gone spell", "Brings summer")], now
    return "left off once taken out; kept while its season still runs"


@case
def t_the_game_reads_every_rule_as_season_py_does():
    """Every day of 2026 to 2028, a leap year among them: the game's event rules and windows
    agree with season.py's event_on() on each, for each kind of rule there is."""
    specs = {
        "w": ((12, 24), (12, 26)), "wrap": ((12, 26), (1, 6)), "leap": ((2, 28), (3, 1)),
        "wk": {"weekdays": ("sat", "sun")}, "pay": {"days": (1, 15, -1)},
        "first_mon": {"weekdays": ("mon",), "weeks": (1,)},
        "last_fri": {"weekdays": ("fri",), "weeks": (-1,)},
        "f13": {"weekdays": ("fri",), "days": (13,)},
        "winter_wk": {"weekdays": ("sat", "sun"), "within": ((12, 1), (2, 28))},
        "months": {"months": (12, 1, 2), "days": (-2,)},
    }
    text, keys = calendar(own={}, events=specs, periods={}, spells={})
    lua, g = tcal.build(2026, 1, 1, calendar=text)
    yours, item_on = tcal.probe(lua, g, "YOURS", "item_on")
    events = {yours.events[i].name: yours.events[i] for i in range(1, len(yours.events) + 1)}
    assert set(events) == set(specs), sorted(events)
    day_of = lua.eval("function(y, m, d) local t = os.date('*t', os.time({year = y, "
                      "month = m, day = d, hour = 12})) t.iso = string.format("
                      "'%04d-%02d-%02d', y, m, d) return t end")
    day, checked, on = datetime.date(2026, 1, 1), 0, 0
    while day.year <= 2028:
        t = day_of(day.year, day.month, day.day)
        for name, spec in specs.items():
            want = season.event_on(day, spec)
            got = bool(item_on(events[name], t, None))
            assert got == want, "%s on %s: game %s, season.py %s" % (name, day, got, want)
            checked += 1
            on += want
        day += datetime.timedelta(days=1)
    return "%d rule-days over 3 years agree, %d of them on" % (checked, on)


@case
def t_the_start_tells_of_the_player_s_own():
    """After the greeting, a message for each of the player's own that is on, unless MCM's
    switch for it is off; a spell the greeting named already is not told twice. With the
    dice on, the greeting promises no next season."""
    text, keys = calendar(spell=("summer", "Indian summer", "2026-10-16", "2026-10-19"),
                          today=("2026-10-17", [("Indian summer", "2026-10-16", "2026-10-19",
                                                 "summer")], []))
    sent = []

    def world(mcm):
        lua, g = tcal.build(2026, 10, 17, calendar=text, mcm=mcm)
        g.CreateTimeEvent = lambda ev, act, delay, fn, *a: fn()
        g.news_manager = lua.table_from({"send_tip": lambda a, msg, *r: sent.append(msg)})
        return lua, g

    lua, g = world({"seasons_zone/main/blend_days": 0})
    (announce,) = tcal.probe(lua, g, "pda_announce")
    announce()
    g.zzz_seasons_of_the_zone.announce_yours(0, True)
    assert sent == ["Summer in the Zone for now: Indian summer, until October 19, 2026.",
                    "Hunter's moon in the Zone, until October 31, 2026.",
                    "Weekend in the Zone, until October 18, 2026."], sent
    # the switch off for Hunter's moon, and no greeting: the spell is told, the moon is not
    del sent[:]
    lua, g = world({"seasons_zone/yours/ann_" + keys[("own", "Hunter's moon")]: False})
    g.zzz_seasons_of_the_zone.announce_yours(0, False)
    assert sent == ["Weekend in the Zone, until October 18, 2026.",
                    "Indian summer in the Zone, until October 19, 2026."], sent
    # the dice on, nothing rolled: the season and the date, and the dice again
    del sent[:]
    text2, _ = calendar(own={}, events={}, periods={}, spells={})
    lua, g = tcal.build(2026, 10, 3, calendar=text2,
                        mcm={"seasons_zone/main/dice": True,
                             "seasons_zone/main/blend_days": 0})
    g.news_manager = lua.table_from({"send_tip": lambda a, msg, *r: sent.append(msg)})
    (announce,) = tcal.probe(lua, g, "pda_announce")
    announce()
    assert sent == ["Autumn in the Zone. October 3, 2026. The dice roll again at the next "
                    "launch."], sent
    return "greeting, then 2 of yours; a switch off silences one; the dice promise nothing"


@case
def t_silence_drops_every_message():
    """MCM's "PDA notifications" off, which the Silence button on the app's pages writes: the
    greeting, the player's own and a turn while playing all go unsent, whatever their own
    switches say, and the log names each one dropped. Asked at sending time, so a message
    queued before the switch went off is dropped too."""
    text, _ = calendar(spell=("summer", "Indian summer", "2026-10-16", "2026-10-19"),
                       today=("2026-10-17", [("Indian summer", "2026-10-16", "2026-10-19",
                                              "summer")], []))
    sent = []
    mcm = {"seasons_zone/main/blend_days": 0, "seasons_zone/main/pda_news": False}
    lua, g = tcal.build(2026, 10, 17, calendar=text, mcm=mcm)
    queued = []
    g.CreateTimeEvent = lambda ev, act, delay, fn, *a: queued.append(fn)
    g.news_manager = lua.table_from({"send_tip": lambda a, msg, *r: sent.append(msg)})
    (announce,) = tcal.probe(lua, g, "pda_announce")
    announce()
    g.zzz_seasons_of_the_zone.announce_yours(0, True)
    for fn in queued:
        fn()
    assert sent == [], sent
    dropped = [l for l in tcal.LOG if "(silenced)" in l]
    assert len(dropped) == 3, tcal.LOG
    # on again: the same three go out; queued while on and silenced before they fire: dropped
    mcm["seasons_zone/main/pda_news"] = True
    del queued[:]
    announce()
    g.zzz_seasons_of_the_zone.announce_yours(0, True)
    for fn in queued:
        fn()
    assert len(sent) == 3, sent
    del sent[:], queued[:]
    g.zzz_seasons_of_the_zone.announce_yours(0, True)
    mcm["seasons_zone/main/pda_news"] = False
    for fn in queued:
        fn()
    assert queued and sent == [], (len(queued), sent)
    return "silenced, 3 messages dropped and logged; on again, 3 sent; queued, then dropped"


@case
def t_a_turn_while_playing_is_told():
    """The day moves on while playing: a message as winter draws near, another as it comes,
    the ground's at the next launch since autumn is staged, and one as a season of the
    player's own begins. None at the first look, none twice, none with the season pinned,
    and none with MCM's switch off."""
    text, keys = calendar()

    def play(dates, mcm=None, staged=None):
        lua, g = tcal.build(2026, 10, 8, calendar=text, mcm=mcm,
                            staged=staged or {"season": "autumn", "staging": "on"})
        lua.execute(tcal.CLOCK)
        clock = g.clock_os()
        g.os = clock
        sent = []
        g.CreateTimeEvent = lambda ev, act, delay, fn, *a: fn()
        g.news_manager = lua.table_from({"send_tip": lambda a, msg, *r: sent.append(msg)})
        out = []
        for m, d in dates:
            clock.set(2026, m, d)
            del sent[:]
            g.zzz_seasons_of_the_zone.turn_tick()
            out.append(list(sent))
        return out

    # Thursday the 8th, Saturday the 10th, a Sunday, the next Sunday and Monday, Sunday
    # the 1st and the Monday after: the weekend begins twice, and is told as it does
    days = [(10, 8), (10, 10), (10, 11), (10, 25), (10, 26), (11, 1), (11, 2)]
    got = play(days)
    assert got == [[],
                   ["Hunter's moon comes to the Zone, until October 31, 2026.",
                    "Weekend comes to the Zone, until October 11, 2026."],
                   [],
                   ["Winter is near: it reaches the Zone in 7 days."],
                   [],
                   ["Winter has come to the Zone. Its ground follows at the next launch "
                    "through play.bat.", "Weekend comes to the Zone today."],
                   []], got
    # with winter staged already there is no ground to wait for
    got = play([(10, 31), (11, 1)], staged={"season": "winter", "staging": "on"})
    assert got[1] == ["Winter has come to the Zone."], got
    # a pin fixes the season: the moon still begins, no turn is told
    got = play(days, mcm={"seasons_zone/main/mode": "summer"})
    assert [m for m in sum(got, []) if "Weekend" not in m] == [
        "Hunter's moon comes to the Zone, until October 31, 2026."], got
    # MCM's switches off: neither the turn nor the moon nor the weekend
    got = play(days, mcm={"seasons_zone/main/pda_turns": False,
                          "seasons_zone/yours/ann_" + keys[("own", "Hunter's moon")]: False,
                          "seasons_zone/yours/ann_" + keys[("event", "weekend")]: False})
    assert sum(got, []) == [], got
    return "the moon, winter near, winter come with its ground; quiet when pinned or off"


@case
def t_mcm_has_a_switch_for_each_of_the_player_s_own():
    """Your calendar: a heading for each kind and a switch for each one, on by default, by
    the key season.py gives it; no page for a player with none."""
    text, keys = calendar()
    lua, g = tcal.build(2026, 7, 1, calendar=text)
    src = io.open(os.path.join(tcal.SCRIPTS, "zzz_seasons_of_the_zone_mcm.script"),
                  encoding="utf-8").read()
    op = g.load_in(src, "zzz_seasons_of_the_zone_mcm", g).on_mcm_load()
    pages = {op.gr[i].id: op.gr[i] for i in range(1, len(op.gr) + 1)}
    assert "yours" in pages and pages["yours"].text == "ui_mcm_seasons_zone_page_yours"
    opts = [pages["yours"].gr[i] for i in range(1, len(pages["yours"].gr) + 1)]
    checks = [(o.id, o.hint, o["def"]) for o in opts if o.type == "check"]
    want = []
    for kind, table in (("own", OWN), ("event", EVENTS), ("period", PERIODS),
                        ("spell", SPELLS)):
        ordered = (sorted(table, key=lambda n: (tuple(table[n][0]), n.casefold()))
                   if kind == "own" else sorted(table, key=lambda n: (n.casefold(), n))
                   if kind != "period" else sorted(table, key=lambda n: tuple(table[n])))
        want += [("ann_" + keys[(kind, n)], "seasons_zone_ann_" + keys[(kind, n)], True)
                 for n in ordered]
    assert checks == want, checks
    heads = [o.text for o in opts if o.type == "desc"][1:]
    assert heads == ["ui_mcm_seasons_zone_yours_own", "ui_mcm_seasons_zone_yours_event",
                     "ui_mcm_seasons_zone_yours_period", "ui_mcm_seasons_zone_yours_spell"]
    main = [pages["main"].gr[i].id for i in range(1, len(pages["main"].gr) + 1)]
    assert "pda_turns" in main, main
    text, _ = calendar(own={}, events={}, periods={}, spells={})
    lua, g = tcal.build(2026, 7, 1, calendar=text)
    op = g.load_in(src, "zzz_seasons_of_the_zone_mcm", g).on_mcm_load()
    assert "yours" not in [op.gr[i].id for i in range(1, len(op.gr) + 1)]
    return "%d switches under 4 headings; none without any" % len(checks)


@case
def t_play_bat_hands_the_player_s_own_to_the_game():
    """season.py apply writes them into season_calendar.ltx, and the labels of their MCM
    switches in English and Russian; a configure.bat change hands them over too. With none,
    both files are the stubs the release ships."""
    config = ("OWN_SEASONS = %r\nEVENTS = %r\nPERIODS = %r\nSPELLS = %r\n"
              % (OWN, EVENTS, PERIODS, SPELLS))
    with tempfile.TemporaryDirectory() as d:
        tc.install(d, config=config)
        cal, _ = tc.with_mod(d)
        text_dir = os.path.join(os.path.dirname(cal), "text")
        os.makedirs(text_dir)
        rc, out = tc.run(d, "apply", tool="season.py",
                         env=dict(os.environ, PYTHONIOENCODING="utf-8"))
        assert rc == 0, out
        body = io.open(cal, encoding="cp1251").read()
        for part in ("[own]", "1_name = Wormhole season", "2_name = Hunter's moon",
                     "[events]", "4_weekdays = sat, sun", "[periods]", "1_from = 07-01",
                     "[spells]", "1_in = autumn", "2_chance = 0.5", "2_in = autumn, Hunter's moon"):
            assert part in body, (part, body)
        with tables() as s:
            keys = s.your_keys()
        for lang in ("eng", "rus"):
            xml = io.open(os.path.join(text_dir, lang, season.YOURS_XML), encoding="cp1251").read()
            for (kind, name), key in keys.items():
                assert 'id="ui_mcm_seasons_zone_ann_%s"' % key in xml, (lang, key)
            assert ("&quot;" not in xml) and ("Hunter's moon" in xml), xml[:400]

    # a change made in configure.bat reaches the game without play.bat
    with tempfile.TemporaryDirectory() as d:
        tc.install(d, config="")
        cal, _ = tc.with_mod(d)
        os.makedirs(os.path.join(os.path.dirname(cal), "text"))
        rc, out = tc.run(d, "event", "christmas", "12-24", "12-26")
        assert rc == 0, out
        body = io.open(cal, encoding="cp1251").read()
        assert "[events]" in body and "1_name = christmas" in body, body

    # none: the stubs, byte for byte
    with tempfile.TemporaryDirectory() as d:
        tc.install(d, config="")
        cal, _ = tc.with_mod(d)
        text_dir = os.path.join(os.path.dirname(cal), "text")
        os.makedirs(text_dir)
        rc, out = tc.run(d, "apply", tool="season.py",
                         env=dict(os.environ, PYTHONIOENCODING="utf-8"))
        assert rc == 0, out
        assert io.open(cal, encoding="cp1251", newline="").read() == \
            build_release.STUB_CALENDAR
        for lang in ("eng", "rus"):
            got = io.open(os.path.join(text_dir, lang, season.YOURS_XML), encoding="cp1251",
                          newline="").read()
            assert got == build_release.STUB_YOURS, (lang, got)
    shipped = [os.path.join(tcal.SCRIPTS, "..", "configs", "text", lang, season.YOURS_XML)
               for lang in ("eng", "rus")]
    assert all(io.open(p, encoding="cp1251", newline="").read() == build_release.STUB_YOURS
               for p in shipped), "the repo's stubs are not the release's"
    return "4 sections and %d labels in 2 languages; configure hands an event over; stubs" % (
        len(keys))


@case
def t_the_api_and_the_tile_follow_what_is_on():
    """sotz_api.calendar().on lists what is on beside the season; the launcher tile and the
    Forecast page's bar show the season the world runs."""
    text, _ = calendar(roll=("winter", 5, 25))
    lua, g = tcal.build(2026, 10, 17, calendar=text)
    src = io.open(os.path.join(tcal.SCRIPTS, "sotz_api.script"), encoding="utf-8").read()
    cal = g.load_in(src, "sotz_api", g).calendar()
    on = [(o.kind, o.name, o.last) for o in items(cal.on)]
    assert on == [("own", "Hunter's moon", "2026-10-31"), ("event", "weekend", "2026-10-18")], on
    assert cal.season == "autumn", "calendar() no longer gives the calendar's season"
    assert g.zzz_seasons_of_the_zone.forecast_page().bar == "ui_season_hdr_winter"
    mac = io.open(os.path.join(tcal.SCRIPTS, "z_seasons_pda_mac.script"),
                  encoding="utf-8").read()
    assert "season_now().key" in mac and "calendar_page().season" not in mac
    return "on: the moon and the weekend; the bar and the tile run on the rolled winter"


if __name__ == "__main__":
    print("  your calendar, under %s for the game's side" % tcal.LUA_NAME)
    bad = 0
    for fn in CASES:
        try:
            print("  PASS  %-58s %s" % (fn.__name__[2:], fn()))
        except AssertionError as e:
            bad += 1
            print("  FAIL  %-58s %s" % (fn.__name__[2:], e))
        except Exception as e:
            bad += 1
            print("  ERROR %-58s %s: %s" % (fn.__name__[2:], type(e).__name__, e))
    print("\n  %d/%d passed" % (len(CASES) - bad, len(CASES)))
    sys.exit(1 if bad else 0)
