"""Putting the tools in the GAMMA folder: the installer, configure.bat and play.bat.

MO2 installs the zip into mods\\<name>\\, and the tools run from the GAMMA folder two
levels up. configure.bat opened in the mod's folder runs the installer; each case builds
a GAMMA folder with the mod in it as the zip lays it out, runs the installer the way a
player would - the batch file, the command, the window - and checks the files on disk.
The build's own install checks run here too, on the same kind of GAMMA folder.

  python _tools/test_install.py
"""
import contextlib
import io
import os
import re
import shutil
import stat
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.dont_write_bytecode = True
import build_release                                            # noqa: E402
import installer                                                # noqa: E402

VERSION = installer.version_of(os.path.join(HERE, "season.py"))
NAME = "SeasonsOfTheZone"           # MO2's default name for the mod: the zip's
ENTRIES = ("Anomaly (DX11-AVX)", "Anomaly (DX11)", "Anomaly (DX9-AVX)")
SEASON = os.path.join("_tools", "season.py")
CRLF = "\r\n"
# no bytecode caches in the sandboxes, so a file there is only ever what a step wrote
ENV = dict(os.environ, PYTHONIOENCODING="utf-8", PYTHONDONTWRITEBYTECODE="1")
SHORTCUT = re.compile(r'(?m)^(set "SHORTCUT=)([^"]*)(")')
OLD = 946684800                     # 2000-01-01: the time a file keeps unless rewritten
CASES = []


def case(fn):
    CASES.append(fn)
    return fn


# --- a GAMMA folder with the mod in it ----------------------------------------------------

def gamma(d, name=NAME):
    """A GAMMA folder in `d`: ModOrganizer.ini with MO2's executable entries, a profile,
    and the mod in mods\\<name>\\ as the zip lays it out, with no tools of its own yet.
    Returns (the GAMMA folder, the mod's folder)."""
    root = os.path.join(d, "GAMMA")
    mod = os.path.join(root, "mods", name)
    os.makedirs(os.path.join(root, "profiles", "Default"))
    ini = (["[General]", "selected_profile=@ByteArray(Default)", "", "[customExecutables]",
            "size=%d" % len(ENTRIES)]
           + ["%d\\title=%s" % (i, t) for i, t in enumerate(ENTRIES, 1)])
    io.open(os.path.join(root, "ModOrganizer.ini"), "w", encoding="utf-8",
            newline="").write(CRLF.join(ini) + CRLF)
    io.open(os.path.join(root, "profiles", "Default", "modlist.txt"), "w", encoding="utf-8",
            newline="").write("# This file was automatically generated by Mod Organizer."
                              + CRLF + "+" + name + CRLF)
    unzipped(mod)
    return root, mod


def unzipped(mod):
    """The mod's folder as MO2 installs the zip: the tools the build ships, the worked
    example, the shipped presets, the two batch files, and the mod's own script."""
    tools = os.path.join(mod, "_tools")
    os.makedirs(os.path.join(tools, "presets"))
    for f in build_release.TOOL_FILES:
        shutil.copy2(os.path.join(HERE, f), tools)
    example = os.path.join(HERE, "seasons_config.example.py")
    if os.path.isfile(example):
        shutil.copy2(example, tools)
    else:                           # an install's _tools: the build writes the example
        put(mod, os.path.join("_tools", "seasons_config.example.py"), b"LAYOUT = {}\r\n")
    for f in os.listdir(os.path.join(HERE, "presets")):
        p = os.path.join(HERE, "presets", f)
        if not installer.saved_by_player(open(p, "rb").read()):
            shutil.copy2(p, os.path.join(tools, "presets"))
    os.makedirs(os.path.join(tools, "lang"))
    for f in os.listdir(os.path.join(HERE, "lang")):
        if f.endswith(build_release.LANG_FILES):
            shutil.copy2(os.path.join(HERE, "lang", f), os.path.join(tools, "lang"))
    for f in ("play.bat", "configure.bat"):
        build_release.write_crlf(os.path.join(REPO, f), os.path.join(mod, f))
    put(mod, os.path.join(*build_release.MARKER.split("/")), b"-- marker")


def shipped(mod):
    """What the installer has to copy, as paths under the mod's folder: every .py in its
    _tools but a seasons_config.py, the presets, the translations, and the two batch
    files."""
    tools = os.path.join(mod, "_tools")
    return sorted([os.path.join("_tools", f) for f in os.listdir(tools)
                   if f.endswith(".py") and f != "seasons_config.py"]
                  + [os.path.join("_tools", "presets", f)
                     for f in os.listdir(os.path.join(tools, "presets"))]
                  + [os.path.join("_tools", "lang", f)
                     for f in os.listdir(os.path.join(tools, "lang"))]
                  + ["configure.bat", "play.bat"])


def read(folder, rel):
    p = os.path.join(folder, rel)
    return open(p, "rb").read() if os.path.isfile(p) else None


def put(folder, rel, data):
    p = os.path.join(folder, rel)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    open(p, "wb").write(data)


def with_entry(bat, title):
    """play.bat's bytes, set to start `title`."""
    text, n = SHORTCUT.subn(lambda m: m.group(1) + title + m.group(3), bat.decode("ascii"),
                            count=1)
    assert n == 1, "play.bat has no SHORTCUT line"
    return text.encode("ascii")


def entry(bat):
    return SHORTCUT.search(bat.decode("ascii")).group(2)


# two entries MO2 lists that play.bat doesn't start on its own: the player's picks
MINE, OTHER = [e for e in ENTRIES if e != entry(open(os.path.join(REPO, "play.bat"),
                                                     "rb").read())][:2]


def set_version(root, version=None):
    """The GAMMA folder's season.py with another VERSION, or none, as before 1.9.0."""
    text = read(root, SEASON).decode("utf-8")
    if version is None:
        text, n = re.subn(r"(?m)^VERSION = [^\n]*\n", "", text)
    else:
        text, n = re.subn(r'(?m)^(VERSION = )"[^"]*"', r'\g<1>"%s"' % version, text)
    assert n == 1, "season.py has no VERSION line"
    put(root, SEASON, text.encode("utf-8"))


def old(root, mod, version=None):
    """The tools as copying them by hand left them in the GAMMA folder: a season.py from
    before VERSION (or with `version`), no installer.py or guide.py, and an older
    config_edit.py, play.bat and Polesia preset. Six files for an install to change."""
    for rel in shipped(mod):
        put(root, rel, read(mod, rel))
    set_version(root, version)
    for rel in ("installer.py", "guide.py"):
        os.remove(os.path.join(root, "_tools", rel))
    for rel, before, after in ((os.path.join("_tools", "config_edit.py"), b"", b"# older\r\n"),
                               ("play.bat", b"REM  an older play.bat\r\n", b""),
                               (os.path.join("_tools", "presets", "Polesia.json"), b"", b" ")):
        put(root, rel, before + read(root, rel) + after)


def preset(shipped):
    """A preset: one that comes with the tools, or one the player saved."""
    return ('{\n  "seasons_of_the_zone_preset": 1,\n  "shipped": %s,\n  "about": "",\n'
            '  "calendar": null\n}\n' % ("true" if shipped else "false")).encode("utf-8")


def age(root):
    """Date every file outside mods\\ back to 2000, so a rewrite shows."""
    for rel in snapshot(root):
        os.utime(os.path.join(root, rel), (OLD, OLD))


def snapshot(root):
    """{path: (bytes, time written)} for every file in the GAMMA folder outside mods\\."""
    out = {}
    for r, dirs, files in os.walk(root):
        dirs[:] = [x for x in dirs if os.path.join(r, x) != os.path.join(root, "mods")]
        for f in files:
            p = os.path.join(r, f)
            out[os.path.relpath(p, root)] = (open(p, "rb").read(), int(os.stat(p).st_mtime))
    return out


# --- running it ---------------------------------------------------------------------------

def install(folder, *args):
    """configure.py install from `folder`'s own tools, in `folder`, as configure.bat runs
    it: (exit code, output)."""
    r = subprocess.run([sys.executable, os.path.join(folder, "_tools", "configure.py"),
                        "install"] + list(args), cwd=folder, capture_output=True, text=True,
                       encoding="utf-8", errors="replace", env=ENV, timeout=120)
    out = r.stdout + r.stderr
    assert "Traceback" not in out, out
    return r.returncode, out


def batch(folder, name, *args):
    """A batch file run in its folder with nobody at the keyboard, so pause goes straight
    on: (exit code, output)."""
    r = subprocess.run(["cmd", "/c", ".\\" + name] + list(args), cwd=folder,
                       stdin=subprocess.DEVNULL, capture_output=True, text=True,
                       encoding="utf-8", errors="replace", env=ENV, timeout=120)
    return r.returncode, r.stdout + r.stderr


def drive(tools, driver, *args):
    """Run `driver` with `tools` first on the path: (exit code, output). A window left
    waiting for a click fails the case at the timeout."""
    with tempfile.TemporaryDirectory() as t:
        p = os.path.join(t, "drive.py")
        io.open(p, "w", encoding="utf-8").write(
            "import sys\nsys.path.insert(0, %r)\n" % tools + driver)
        r = subprocess.run([sys.executable, p] + list(args), cwd=os.path.dirname(tools),
                           capture_output=True, text=True, encoding="utf-8",
                           errors="replace", env=ENV, timeout=60)
    return r.returncode, r.stdout + r.stderr


def quiet(fn, *args):
    """fn(*args) with what it prints caught: (its result, the text)."""
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        got = fn(*args)
    return got, buf.getvalue()


# installer.main without --yes, the setup's hand-off recorded rather than started. A window
# that opens gets its buttons pressed in the order given on the command line; before each
# press the driver prints what the window shows and the version season.py has there.
WINDOW = r'''
import argparse, os, sys
import tkinter as tk
from tkinter import messagebox
import installer

handed, asked, answers = [], [], [False, True]
installer.hand_off = handed.append


def askyesno(title, message, **kw):
    asked.append(kw.get("default"))
    return answers.pop(0)


messagebox.askyesno = askyesno
PRESS = sys.argv[1:]
THERE = os.path.join(os.path.dirname(os.path.dirname(installer.SOURCE)), "_tools",
                     "season.py")
RealTk = tk.Tk


def widgets(w):
    for c in w.winfo_children():
        yield c
        yield from widgets(c)


class Tk(RealTk):
    def __init__(self, *a, **k):
        RealTk.__init__(self, *a, **k)
        self.after(300, self.press)

    def press(self):
        try:
            win = [w for w in self.winfo_children() if isinstance(w, tk.Toplevel)][-1]
            print("PAGE " + " | ".join(str(w.cget("text")) for w in widgets(win)
                                       if w.winfo_class() == "TLabel"))
            print("THERE %s" % installer.version_of(THERE))
            buttons = {str(b.cget("text")): b for b in widgets(win)
                       if b.winfo_class() == "TButton"}
            buttons[PRESS.pop(0)].invoke()
        except Exception as e:
            print("STUCK %s: %s" % (type(e).__name__, e))
            self.destroy()
            return
        if PRESS:
            self.after(300, self.press)


tk.Tk = Tk
try:
    installer.main(argparse.Namespace(yes=False))
    print("EXIT 0")
except SystemExit as e:
    print("EXIT %s" % e.code)
print("HANDED " + " | ".join(handed))
print("ASKED " + " | ".join(asked))
'''


def pages(out):
    return [l[5:] for l in out.splitlines() if l.startswith("PAGE ")]


# --- the cases ----------------------------------------------------------------------------

@case
def t_a_first_install_puts_the_tools_in_the_gamma_folder():
    with tempfile.TemporaryDirectory() as d:
        root, mod = gamma(d)
        rc, out = install(mod, "--yes")
        want = shipped(mod)
        assert rc == 0 and "Installing the tools into your GAMMA folder, %s." % root in out, out
        words = [f for f in os.listdir(os.path.join(HERE, "lang"))
                 if f.endswith(build_release.LANG_FILES)]
        assert len(want) == len(build_release.TOOL_FILES) + 7 + len(words) and \
            "play.bat" in want and os.path.join("_tools", "lang", "ru.po") in want, want
        wrong = [f for f in want if read(root, f) != read(mod, f)]
        assert not wrong, "not there as the zip has them: %s\n%s" % (wrong, out)
        extra = set(snapshot(root)) - set(want) - {
            "ModOrganizer.ini", os.path.join("profiles", "Default", "modlist.txt")}
        assert not extra, "also wrote %s" % sorted(extra)
        assert "Files: %d new." % len(want) in out, out
        assert out.count("    new      ") == len(want), "not every file listed:\n" + out
        assert "From now on, open configure.bat and play.bat in your GAMMA folder" in out, out
    return "%d files, byte for byte, from a mod under MO2's default name; nothing else" % len(
        want)


@case
def t_an_update_keeps_what_is_the_player_s():
    """Tools copied by hand before there was an installer, the player's settings, backups
    and presets beside them, and play.bat set to another of MO2's entries. The tools now
    ship a preset under a name the player used, and a seasons_config.py left in the mod's
    folder must not travel."""
    with tempfile.TemporaryDirectory() as d:
        root, mod = gamma(d)
        old(root, mod)
        winter = os.path.join("_tools", "presets", "Winter.json")
        mine = {os.path.join("_tools", "seasons_config.py"): b"TOGGLE_MODS = {}\r\n",
                os.path.join("_tools", "seasons_config.py.bak"): b"TOGGLE_MODS = {1: 2}\r\n",
                os.path.join("_tools", "seasons_config.py.before-20260901-120000.bak"): b"x",
                os.path.join("_tools", "presets", "Mine.json"): preset(False),
                winter: preset(False)}
        for rel, data in mine.items():
            put(root, rel, data)
        put(mod, winter, preset(True))
        put(mod, os.path.join("_tools", "seasons_config.py"), b"# made here by mistake\r\n")
        put(root, "play.bat", with_entry(read(root, "play.bat"), MINE))
        rc, out = install(mod, "--yes")
        assert rc == 0, out
        assert ("Updating the tools in your GAMMA folder, %s: an older version there, %s "
                "here." % (root, VERSION)) in out, out
        touched = [rel for rel, data in mine.items() if read(root, rel) != data]
        assert not touched, "changed the player's %s:\n%s" % (touched, out)
        stale = [f for f in shipped(mod) if f not in (winter, "play.bat")
                 and read(root, f) != read(mod, f)]
        assert not stale, "not updated: %s\n%s" % (stale, out)
        assert read(root, "play.bat") == with_entry(read(mod, "play.bat"), MINE), \
            "play.bat is not the new one starting %s:\n%s" % (MINE, out)
        assert 'play.bat keeps starting "%s".' % MINE in out, out
        assert "    kept     %s - yours" % winter in out, out
        assert "Files: 2 new, 4 updated, %d the same, 1 of your presets kept." % (
            len(shipped(mod)) - 7) in out, out
        assert "Done. Your settings there are kept." in out, out
    return ("seasons_config.py, 2 backups, 2 presets of the player's and play.bat's entry "
            "kept; 6 tools updated")


@case
def t_an_entry_a_batch_file_can_t_hold_is_named():
    """An entry whose name has a character a batch file reads as something else isn't
    written into play.bat; the new one starts its own, and the player is told why."""
    with tempfile.TemporaryDirectory() as d:
        root, mod = gamma(d)
        install(mod, "--yes")
        put(root, "play.bat", with_entry(read(root, "play.bat"), "Anomaly & Co"))
        rc, out = install(mod, "--yes")
        assert rc == 0 and ('play.bat starts "%s" from now on: the entry it started, "Anomaly '
                            '& Co", has a character' % entry(read(mod, "play.bat"))) in out, out
        assert read(root, "play.bat") == read(mod, "play.bat"), out
    return "play.bat back on its own entry, and the name it had given"


@case
def t_a_second_run_writes_nothing():
    with tempfile.TemporaryDirectory() as d:
        root, mod = gamma(d)
        rc, out = install(mod, "--yes")
        assert rc == 0, out
        # compared as it would be written, play.bat on an entry of the player's is the same
        put(root, "play.bat", with_entry(read(root, "play.bat"), OTHER))
        age(root)
        before = snapshot(root)
        rc, out = install(mod, "--yes")
        assert rc == 0 and "The tools in your GAMMA folder, %s, are up to date (%s)." % (
            root, VERSION) in out, out
        changed = [f for f in before if snapshot(root)[f] != before[f]]
        assert not changed, "rewrote %s:\n%s" % (changed, out)
        assert entry(read(root, "play.bat")) == OTHER
    return "up to date, play.bat on an entry of its own; not one file rewritten"


@case
def t_newer_tools_there_are_not_replaced_with_yes():
    """A downgrade is refused from the console. Versions compare as numbers: x.19.0 is
    newer than x.9.0, though it sorts before it as text."""
    major, minor = VERSION.split(".")[:2]
    later = "%s.%d.0" % (major, int(minor) + 10)
    with tempfile.TemporaryDirectory() as d:
        root, mod = gamma(d)
        install(mod, "--yes")
        set_version(root, later)
        put(root, os.path.join("_tools", "config_edit.py"), b"# newer\r\n")
        age(root)
        before = snapshot(root)
        rc, out = install(mod, "--yes")
        assert rc == 1 and "are newer than these: %s there, %s here." % (
            later, VERSION) in out and "Nothing was changed" in out and mod in out, out
        assert snapshot(root) == before, "a refused downgrade changed files"
        # an older VERSION there is an update
        set_version(root, "0.1.0")
        rc, out = install(mod, "--yes")
        assert rc == 0 and "0.1.0 there, %s here." % VERSION in out, out
        assert read(root, SEASON) == read(mod, SEASON), out
    return "%s there refused, nothing changed; 0.1.0 there updated" % later


@case
def t_from_the_gamma_folder_it_goes_on_to_the_setup():
    with tempfile.TemporaryDirectory() as d:
        root, mod = gamma(d)
        install(mod, "--yes")
        age(root)
        before = snapshot(root)
        rc, out = install(root, "--yes")
        assert rc == 0 and "The tools already run from your GAMMA folder, %s." % (
            root) in out, out
        rc, out = drive(os.path.join(root, "_tools"), WINDOW)
        assert "EXIT 0" in out and "HANDED %s\n" % root in out, out
        assert not pages(out), "opened a window:\n" + out
        assert snapshot(root) == before, "wrote files in the GAMMA folder"
    return "says so; the setup opens from there without a window; nothing written"


@case
def t_without_a_gamma_folder_it_says_where_it_looked():
    with tempfile.TemporaryDirectory() as d:
        down = os.path.join(d, "Downloads")
        mod = os.path.join(down, "Seasons of the Zone")
        unzipped(mod)
        rc, out = install(mod, "--yes")
        assert rc == 1 and "looked in : %s, two folders up" % d in out, out
        assert "ModOrganizer.ini   MISSING" in out and "Nothing has been changed" in out, out
        # one folder up is not where MO2 puts a mod
        io.open(os.path.join(down, "ModOrganizer.ini"), "w").write("[General]\n")
        rc, out = install(mod, "--yes")
        assert rc == 1 and "MISSING" in out, out
        assert os.listdir(d) == ["Downloads"] and sorted(os.listdir(down)) == [
            "ModOrganizer.ini", "Seasons of the Zone"], "wrote outside the mod's folder"
    return "the folder named and ModOrganizer.ini missing; one folder up doesn't count"


@case
def t_each_file_is_written_whole_or_not_at_all():
    """A file is replaced, not written into: a second name for the old one keeps the old
    bytes. One that can't be replaced is named, the count of those copied is said, and no
    temp file is left behind."""
    with tempfile.TemporaryDirectory() as d:
        root, mod = gamma(d)
        old(root, mod)
        edit = os.path.join("_tools", "config_edit.py")
        was = read(root, edit)
        os.link(os.path.join(root, edit), os.path.join(d, "second name.py"))
        before = snapshot(root)
        todo = [f for f in shipped(mod) if read(root, f) != read(mod, f)]
        stuck = os.path.join(root, SEASON)
        os.chmod(stuck, stat.S_IREAD)
        try:
            rc, out = install(mod, "--yes")
        finally:
            os.chmod(stuck, stat.S_IREAD | stat.S_IWRITE)
        after = snapshot(root)
        wrote = [f for f in after if after[f][0] != before.get(f, (None,))[0]]
        m = re.search(r"(\d+) of the (\d+) files were copied; the rest are as they were", out)
        assert rc == 1 and "Couldn't write %s: " % SEASON in out and m, out
        assert (int(m.group(1)), int(m.group(2))) == (len(wrote), len(todo)), (wrote, out)
        assert after[SEASON] == before[SEASON], "season.py changed"
        assert not [f for f in after if f.endswith(".tmp")], "left a temp file"
        rc, out = install(mod, "--yes")
        assert rc == 0 and all(read(root, f) == read(mod, f) for f in todo), out
        assert read(d, "second name.py") == was, "config_edit.py was written into, not replaced"
    return "replaced whole; a read-only one named, %d of %d copied and said so; the next " \
           "run finishes" % (len(wrote), len(todo))


@case
def t_configure_bat_installs_from_the_mod_s_folder():
    with tempfile.TemporaryDirectory() as d:
        root, mod = gamma(d)
        rc, out = batch(mod, "configure.bat", "--yes")
        assert rc == 0 and "Installing the tools into your GAMMA folder" in out, out
        assert "Press any key" not in out, "paused after an install that went through:\n" + out
        missing = [f for f in shipped(mod) if read(root, f) != read(mod, f)]
        assert not missing, "not installed: %s\n%s" % (missing, out)
        # in the GAMMA folder it runs the tools there, with what follows it passed on
        rc, out = batch(root, "configure.bat", "install", "--yes")
        assert rc == 0 and "The tools already run from your GAMMA folder" in out, out
        # a refusal stays on screen until a key, and its exit code comes through
        set_version(root, "99.0.0")
        rc, out = batch(mod, "configure.bat", "--yes")
        assert rc == 1 and "Nothing was changed" in out and "Press any key" in out, out
        # anywhere else, as before
        away = os.path.join(d, "a", "b", "c")
        os.makedirs(away)
        shutil.copy2(os.path.join(mod, "configure.bat"), away)
        rc, out = batch(away, "configure.bat", "--yes")
        assert rc == 1 and "configure.bat has to be in your GAMMA folder" in out, out
    return "installed from the mod's folder; the GAMMA folder's runs its own; elsewhere refused"


@case
def t_play_bat_in_the_mod_s_folder_says_what_to_do():
    with tempfile.TemporaryDirectory() as d:
        root, mod = gamma(d)
        rc, out = batch(mod, "play.bat")
        assert rc == 1 and "This is the copy of play.bat in the mod's folder" in out, out
        assert "configure.bat from this" in out and ('"%s"' % root).lower() in out.lower(), out
        assert "Then start the game with the play.bat there." in out, out
        assert sorted(os.listdir(root)) == ["ModOrganizer.ini", "mods", "profiles"], \
            "play.bat did something:\n" + out
        away = os.path.join(d, "a", "b", "c")
        os.makedirs(away)
        shutil.copy2(os.path.join(mod, "play.bat"), away)
        rc, out = batch(away, "play.bat")
        assert rc == 1 and "play.bat has to be in your GAMMA folder" in out, out
    return "names the GAMMA folder and configure.bat; elsewhere the old message"


@case
def t_the_window_installs_then_goes_on_to_the_setup():
    with tempfile.TemporaryDirectory() as d:
        root, mod = gamma(d)
        old(root, mod, "1.8.3")
        put(root, "play.bat", with_entry(read(root, "play.bat"), MINE))
        rc, out = drive(os.path.join(mod, "_tools"), WINDOW, "Install", "Continue")
        shown = pages(out)
        assert len(shown) == 2 and "EXIT 0" in out and "HANDED %s\n" % root in out, out
        assert shown[0] == " | ".join([
            "Update the tools",
            "It puts play.bat, configure.bat and the _tools folder in your GAMMA folder, %s, "
            "where they run from. Your settings there are kept." % root,
            "1.8.3 there, %s here." % VERSION,
            "Files: 2 new, 4 updated, %d the same." % (len(shipped(mod)) - 6),
            'play.bat keeps starting "%s".' % MINE]), shown[0]
        assert shown[1] == ("Done | From now on, open configure.bat and play.bat in your "
                            "GAMMA folder, %s." % root), shown[1]
        wrong = [f for f in shipped(mod) if f != "play.bat" and read(root, f) != read(mod, f)]
        assert not wrong and entry(read(root, "play.bat")) == MINE, (wrong, out)
        # opened again: up to date, and on to the setup
        rc, out = drive(os.path.join(mod, "_tools"), WINDOW, "Continue")
        assert pages(out) == [
            "Up to date | The tools in your GAMMA folder, %s, are up to date. From now on, "
            "open configure.bat and play.bat there." % root], out
        assert "HANDED %s\n" % root in out, out
    return "what, where, versions, counts and play.bat's entry; Install, Done, Continue"


@case
def t_the_window_can_be_canceled_and_asks_first():
    with tempfile.TemporaryDirectory() as d:
        root, mod = gamma(d)
        rc, out = drive(os.path.join(mod, "_tools"), WINDOW, "Cancel")
        assert pages(out) == [
            "Install the tools | It puts play.bat, configure.bat and the _tools folder in your "
            "GAMMA folder, %s, where they run from. | Files: %d new." % (
                root, len(shipped(mod)))], out
        assert "EXIT 0" in out and "HANDED \n" in out, out
        assert sorted(os.listdir(root)) == ["ModOrganizer.ini", "mods", "profiles"], out
    major, minor = VERSION.split(".")[:2]
    later = "%s.%d.0" % (major, int(minor) + 10)
    with tempfile.TemporaryDirectory() as d:
        root, mod = gamma(d)
        install(mod, "--yes")
        set_version(root, later)
        # Install twice: No, then Yes
        rc, out = drive(os.path.join(mod, "_tools"), WINDOW, "Install", "Install", "Continue")
        shown = pages(out)
        assert "%s there, %s here: the tools there are newer." % (
            later, VERSION) in shown[0], out
        assert "ASKED no | no" in out, "not asked, or not with No as the default:\n" + out
        there = [l[6:] for l in out.splitlines() if l.startswith("THERE ")]
        assert there == [later, later, VERSION], "wrote before a Yes: %s\n%s" % (there, out)
        assert shown[1] == shown[0] and shown[2].startswith("Done"), out
        assert "EXIT 0" in out and "HANDED %s\n" % root in out, out
    return "Cancel writes nothing; a downgrade asks, No by default, and waits for a Yes"


@case
def t_the_window_says_what_stopped_an_install():
    with tempfile.TemporaryDirectory() as d:
        root, mod = gamma(d)
        old(root, mod)
        stuck = os.path.join(root, SEASON)
        os.chmod(stuck, stat.S_IREAD)
        try:
            rc, out = drive(os.path.join(mod, "_tools"), WINDOW, "Install", "Close")
        finally:
            os.chmod(stuck, stat.S_IREAD | stat.S_IWRITE)
        shown = pages(out)
        assert len(shown) == 2 and shown[1].startswith(
            "Not finished | Couldn't write %s: " % SEASON), out
        assert "files were copied; the rest are as they were" in shown[1], out
        assert "EXIT 1" in out and "HANDED \n" in out, out
        # the console behind it says the same, and configure.bat pauses on the exit code
        assert out.count("Couldn't write %s: " % SEASON) == 2, out
    return "the file and the count in the window and the console; exit 1, no setup"


@case
def t_the_setup_opens_from_the_gamma_folder_s_copy():
    """hand_off itself: the GAMMA folder's configure.py, run by this Python, in the GAMMA
    folder."""
    with tempfile.TemporaryDirectory() as d:
        root = os.path.join(d, "GAMMA")
        seen = os.path.join(d, "seen.txt")
        put(root, os.path.join("_tools", "configure.py"), (
            "import os, sys\nopen(%r, 'w').write(repr([sys.executable] + sys.argv + "
            "[os.getcwd()]))\n" % seen).encode("utf-8"))
        installer.hand_off(root).wait(60)
        got = [os.path.normcase(x) for x in eval(open(seen).read())]
        want = [os.path.normcase(x) for x in (sys.executable, os.path.join(
            root, "_tools", "configure.py"), root)]
        assert got == want, (got, want)
        # with the GAMMA folder's configure.bat there, through it: an error pauses there
        ran = os.path.join(d, "ran.txt")
        put(root, "configure.bat", ('@echo off\r\n> "%s" echo %%CD%%\r\n' % ran).encode(
            "ascii"))
        installer.hand_off(root).wait(60)
        assert os.path.normcase(open(ran).read().strip()) == os.path.normcase(root), \
            open(ran).read()
    return ("configure.bat there when it is there, else configure.py by this Python, in the "
            "GAMMA folder")


@case
def t_the_build_installs_the_way_players_do():
    with tempfile.TemporaryDirectory() as d:
        root, mod = gamma(d)
        ok, out = quiet(build_release.verify_installer, root, mod)
        assert ok and out.count(" OK") == 4 and "FAILED" not in out, out
    # an installer that does nothing is caught
    with tempfile.TemporaryDirectory() as d:
        root, mod = gamma(d)
        put(mod, os.path.join("_tools", "installer.py"), b"def main(a):\n    pass\n")
        ok, out = quiet(build_release.verify_installer, root, mod)
        assert not ok and "FAILED" in out, out
    return "4 checks pass on the packaged installer; one that does nothing is refused"


@case
def t_the_build_refuses_a_version_not_in_the_changelog():
    changelog = os.path.join(build_release.OUT, "CHANGELOG.md")
    if not os.path.isfile(changelog):               # a clone: the changelog is at the top
        changelog = os.path.join(REPO, "CHANGELOG.md")
    _, out = quiet(build_release.check_version, os.path.join(HERE, "season.py"), changelog)
    assert "version                %s" % VERSION in out, out
    log = "# Changelog\n\n## 1.9.1 \u2014 2026-10-01\n\n- x\n\n## 1.9.0 \u2014 2026-09-25\n"
    refused = []
    with tempfile.TemporaryDirectory() as d:
        s, c = os.path.join(d, "season.py"), os.path.join(d, "CHANGELOG.md")
        for code, text in (('VERSION = "1.9.1"\n', log),
                           ('VERSION = "1.9.0"\n', log),             # an entry, no new VERSION
                           ('VERSION = "1.9.2"\n', log),             # a VERSION, no entry
                           ('SOTZ = "Seasons of the Zone"\n', log),  # no VERSION
                           ('VERSION = "1.9.1"\n', None)):           # no CHANGELOG.md
            io.open(s, "w", encoding="utf-8").write(code)
            if text is None:
                os.remove(c)
            else:
                io.open(c, "w", encoding="utf-8").write(text)
            try:
                quiet(build_release.check_version, s, c)
                refused.append(False)
            except SystemExit as e:
                assert "refusing to package" in str(e.code), e.code
                refused.append(True)
    assert refused == [False, True, True, True, True], refused
    return "%s matches this changelog; 4 mismatches refused" % VERSION


if __name__ == "__main__":
    print("  installing the tools from the mod's folder")
    bad = 0
    for fn in CASES:
        try:
            print("  PASS  %-50s %s" % (fn.__name__[2:], fn()))
        except AssertionError as e:
            bad += 1
            print("  FAIL  %-50s %s" % (fn.__name__[2:], e))
        except Exception as e:
            bad += 1
            print("  ERROR %-50s %s: %s" % (fn.__name__[2:], type(e).__name__, e))
    print("\n  %d/%d passed" % (len(CASES) - bad, len(CASES)))
    sys.exit(1 if bad else 0)
